# image
dockerfile_builder_image_from: "{{ dest_subdir }}/base{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined else '' }}"
dockerfile_builder_image_version:
  "{{ nginx_version + '.' + (git_commit|default('0')) }}"
