- name: "build images in ansible group"
  when: ansible_host in groups[build_step|default('all')]
  block:
    - name: show build group name
      debug:
        msg: "building images in group: {{ build_step|default('all') }}"

    - name: build
      include_tasks: build.yml
