- name: load image state
  include_tasks: tasks/state/load.yml

- name: set image version related facts
  include_tasks: tasks/builder/version.yml

- name: promote image
  include_tasks: tasks/promote/copy.yml

- name: save image state
  include_tasks: tasks/state/save.yml
