- name: load image state
  include_tasks: tasks/state/load.yml

- name: set release version from saved tag with no bump (major.minor.patch)
  when:
    - version_image_dict is not defined or not version_image_dict
    - version_release_no_bump | default(false)
  vars:
    version_release_dict: "{{ state_yml_tag | default('0.0.1') | release_version_dict }}"
  set_fact:
    version_image_dict: "{{ version_release_dict }}"
    version_image_full: "{{ version_release_dict.full }}"
    version_image_major: "{{ version_release_dict.major }}"
    version_image_minor: "{{ version_release_dict.minor }}"

- name: set image version related facts
  include_tasks: tasks/builder/version.yml

- name: promote image
  include_tasks: tasks/promote/main.yml

- name: save image state
  include_tasks: tasks/state/save.yml
