#!/bin/bash -e
# description: additional entrypoint script for moodle php-fpm

# If nginx is installed
if rpm -q nginx &>/dev/null; then
    # Exit if php-fpm conf file not writable
    if ! [ -w "${PHP_FPM_CONF_FILE}" ]; then
        echo "Nginx installed and ${PHP_FPM_CONF_FILE} not writable...doing nothing here"
        exit 0
    fi
    # Add user, group, all, read permissions to moodledata dir to be accesible by nginx running in another
    # container using this same image. $MOODLE_DATA_READABLE_DIR must be set
    if [ -n "${MOODLE_DATA_READABLE_DIR}" ] && ${MOODLE_DATA_READABLE_DIR,,} && [ -n "${MOODLE_DATA}" ] && [ -d "${MOODLE_DATA}" ]; then
        chmod +r ${MOODLE_DATA}
    fi
fi

# Copy moodle config.php if variable $MOODLE_CONFIG_DIR is set and file does not exist in $MOODLE_APP
if ! [ -z ${MOODLE_CONFIG_DIR+x} ] && [ -f ${MOODLE_CONFIG_DIR}/config.php ] && ! [ -f ${MOODLE_APP}/config.php ] ; then
    cp -L ${MOODLE_CONFIG_DIR}/config.php ${MOODLE_APP}/config.php
    chmod 0400 ${MOODLE_APP}/config.php
fi

# Moodle php ini config
cat << _EOF > "${PHP_CONF_DIR}/50-moodle.ini"
max_input_vars = ${PHP_MAX_INPUT_VARS:-5000}
_EOF
