# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General variables
ENV IMAGE_name=ansible-podman-ci \
    IMAGE_summary="Podman image based on {{ dockerfile_builder_image_based }} for Continuous Integration" \
    IMAGE_description="{{ dockerfile_builder_image_based }} based image with tools like Buildah and Skopeo, for CI" \
    IMAGE_title="Ansible CI image based on {{ dockerfile_builder_image_based }}"

ENV BUILDAH_ISOLATION=chroot \
    BUILDAH_LAYERS=true \
    CONTAINER_BUILDER=podman

RUN echo "Installing podman..."  && \
    $CTR_pkg_mgm install xz gzip tar podman skopeo buildah && \
    rpm -e --nodeps container-selinux && \
    echo "Cleaning..."  && \
    $CTR_pkg_mgm clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*

COPY conf/etc/containers/containers.conf /etc/containers/containers.conf

{% if jx3_version is defined and jx3_version %}
ENV JX3_VERSION="{{ jx3_version }}"
ENV JX3_HOME=/home/.jx3
RUN echo "Installing jx3 version: ${JX3_VERSION}..."  && \
    pushd /tmp && \
    curl -L https://github.com/jenkins-x/jx-cli/releases/download/v${JX3_VERSION}/jx-cli-linux-amd64.tar.gz | tar xzv && \
    mv jx /usr/bin/{{ jx3_binary_name | default('jx') }} && \
    echo "Pre-load jx3 plugins..."  && \
    # {{ jx3_binary_name | default('jx') }} upgrade plugins --mandatory && \
    {{ jx3_binary_name | default('jx') }} gitops version && \
    echo "Cleaning..."  && \
    rm -rf /tmp/* && \
    popd

{% endif %}
{% if oras_version is defined and oras_version %}
ENV ORAS_VERSION="{{ oras_version }}"
RUN echo "Installing oras version: ${ORAS_VERSION}..."  && \
    pushd /tmp && \
    curl -L https://github.com/deislabs/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz | tar xzv && \
    mv oras /usr/bin/{{ oras_binary_name | default('oras') }} && \
    echo "Cleaning..."  && \
    rm -rf /tmp/* && \
    popd

{% endif %}
CMD [ "/bin/bash" ]

# Labels
LABEL name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      maintainer="{{ dockerfile_builder_image_authors }}" \
      description="${IMAGE_description}" \
      org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},{{ dockerfile_builder_image_ocp_tags }}"
