# image
dockerfile_builder_image_from: "{{ dest_subdir }}/nginx"
dockerfile_builder_image_version:
  "{{ nginx_version + '.' + (git_commit|default('0')) }}"

# source dir
src_path: "{{ src_dir }}/{{ src_subdir }}/php-fpm"
