apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_image='quay.io/krestomatio/moodle:4.5@sha256:12b8d11f832dad6662bbce7326ae0ce95a0ab7a25e1a891a9c0b4688dd48966f'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_image//@/\\@}#" \
            roles/v1alpha1/m4e/moodle/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres:15@sha256:cc3d880525619d1efd418a6742bd54abd74a43e2513adb5093e2c4af21cdffcd'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx:1.26@sha256:69b8543e9e3c68ac4bf1acf246767f5c53b0d056ba385b8ecc8cd24e4636cf1a'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Keydb image and its tag
        name: bash
        args:
        - -c
        - |
          keydb_image='quay.io/krestomatio/keydb:6.3.4@sha256:a7b4bea4eeb0aae8ae00fa49a306e6749cee913e0ffa4e8b78288ec2b4697401'
          sed -i \
            "s#^keydb_image:.*#keydb_image: ${keydb_image//@/\\@}#" \
            roles/v1alpha1/database/keydb/defaults/main/keydb.yml
    - command:
        # update PgBouncer image and its tag
        name: bash
        args:
        - -c
        - |
          pgbouncer_image='quay.io/krestomatio/pgbouncer@sha256:2ebbf9f0700b639031a524d0e3431014c04d1cfbe38aed2b31ae3a98211e51fb'
          sed -i \
            "s#^pgbouncer_image:.*#pgbouncer_image: ${pgbouncer_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/pgbouncer.yml
    - command:
        # update NFS Ganesha image and its tag
        name: bash
        args:
        - -c
        - |
          nfs_ganesha_image='quay.io/krestomatio/nfs-ganesha:5.9.10@sha256:eb76dc1aebef21b56ec72ca76d0c4a00c610f57a1cde45dd423d7c6ac90538f1'
          sed -i \
            "s#^ganesha_image:.*#ganesha_image: ${nfs_ganesha_image//@/\\@}#" \
            roles/v1alpha1/nfs/ganesha/defaults/main/ganesha.yml
