apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_image='quay.io/krestomatio/moodle:4.5@sha256:0ad0ddfba774b7bf9b8eeff66cc3459da86f591729f883d1f2a5ee9aaad08880'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_image//@/\\@}#" \
            roles/v1alpha1/m4e/moodle/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres:15@sha256:badaba8084120afe25348021db971bd62b49a7ee9416e780c599c2f8b79488ae'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx:1.26@sha256:9b834bf0a986445aec39033c470f6699a8891ce718acec37b492f26c99b86a10'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Keydb image and its tag
        name: bash
        args:
        - -c
        - |
          keydb_image='quay.io/krestomatio/keydb:6.3.4@sha256:74fa12dd6ae4d49b4a8c67c0e4abc4afd5b0757486c1cca491cef834f4b0dda6'
          sed -i \
            "s#^keydb_image:.*#keydb_image: ${keydb_image//@/\\@}#" \
            roles/v1alpha1/database/keydb/defaults/main/keydb.yml
    - command:
        # update PgBouncer image and its tag
        name: bash
        args:
        - -c
        - |
          pgbouncer_image='quay.io/krestomatio/pgbouncer@sha256:8aa1732e0aea7c393274436c50be322aaa6249883c47267aeb6c3d43a8c1355f'
          sed -i \
            "s#^pgbouncer_image:.*#pgbouncer_image: ${pgbouncer_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/pgbouncer.yml
    - command:
        # update NFS Ganesha image and its tag
        name: bash
        args:
        - -c
        - |
          nfs_ganesha_image='quay.io/krestomatio/nfs-ganesha:5.9.11@sha256:c4bdf5ac6a6b10899c8d931629748ea8ce9f82ba03f8d65d3cad598a2b0925d6'
          sed -i \
            "s#^ganesha_image:.*#ganesha_image: ${nfs_ganesha_image//@/\\@}#" \
            roles/v1alpha1/nfs/ganesha/defaults/main/ganesha.yml
