# {{ ansible_managed  }}
FROM {{ image_from }}

ENV PHP_VERSION="{{ moodle_php_version }}" \
    PHP_VER_SHORT="{{ moodle_php_version | replace('.','') }}" \
    MOODLE_VERSION="{{ moodle_version }}" \
    MOODLE_VER_SHORT="{{ moodle_version | replace('.','') }}" \
    IMAGE_AUTHORS="{{ image_authors }}" \
    TZ="{{ image_timezone }}"

ENV NAME=php${PHP_VER_SHORT}_moodle${MOODLE_VER_SHORT} \
    SUMMARY="PHP $PHP_VERSION for Moodle" \
    DESCRIPTION="This UBI based docker image runs \
    PHP $PHP_VERSION for Moodle" \
    TITLE="PHP ${PHP_VERSION} for Moodle" \
    PHP_FPM_PORT="9000"

LABEL org.opencontainers.image.title="${TITLE}" \
      org.opencontainers.image.authors="${AUTHORS}" \
      org.opencontainers.image.description="${DESCRIPTION}" \
      org.opencontainers.image.version="${MOODLE_VERSION}" \
      name="${NAME}" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.description="${DESCRIPTION}" \
      io.k8s.display-name="${TITLE}" \
      io.openshift.expose-services="${PHP_FPM_PORT}:php-fpm" \
      io.openshift.tags="apache,apache${APACHE_VER_SHORT},apache-${APACHE_VER_SHORT},php,php${PHP_VER_SHORT},php-${PHP_VER_SHORT},moodle,moodle${MOODLE_VER_SHORT},moodle-${MOODLE_VER_SHORT},${NAME}" \
      maintainer="${IMAGE_AUTHORS}"

ENV CUSER=apache \
    CUSER_ID="48" \
    CMD="php-fpm"

ENV PHP_RUN=/run/php-fpm \
    PHP_CONF_DIR=/etc/php.d \
    PHP_CONF_FILE=/etc/php.ini \
    PHP_SYSCONF_PATH=/etc \
    PHP_MODULES_DIR=/usr/lib64/php/modules/ \
    PHP_FPM_CONF_DIR=/etc/php-fpm.d \
    PHP_FPM_CONF_FILE=/etc/php-fpm.conf \
    PHP_FPM_POOL_FILE=/etc/php-fpm.d/www.conf \
    HTTPD_PUBLIC_PATH=/var/www/html

# php-curl included in php-common
# php-zip as php-pecl-zip
# php-xsl as php-xml
ENV INSTALL_PKGS="php-fpm php-cli php-gd php-intl php-ldap \
                  php-opcache php-pgsql php-soap php-xmlrpc  \
                  php-xml php-pecl-zip php-mbstring"

COPY conf/usr/bin/* /usr/bin/
COPY conf/etc/php.d/* /etc/php.d/

RUN container-setup
RUN install-pkgs ${INSTALL_PKGS}
RUN php-fpm-setup

WORKDIR ${HTTPD_PUBLIC_PATH}

USER ${CUSER_ID}

STOPSIGNAL SIGQUIT

EXPOSE ${PHP_FPM_PORT}

ENTRYPOINT ["container-entrypoint"]

CMD $CMD
