# {{ ansible_managed  }}
ARG ARG_IMAGE_FROM={{ dockerfile_builder_image_from }}
FROM ${ARG_IMAGE_FROM}

# General variables
ENV IMAGE_NAME=ansible-operator-ci \
    IMAGE_SUMMARY="Ansible Operator SDK image based on {{ dockerfile_builder_image_based }} for Continuous Integration" \
    IMAGE_DESCRIPTION="{{ dockerfile_builder_image_based }} based image with Ansible Operator SDK" \
    IMAGE_TITLE="Ansible Operator SDK CI image based on {{ dockerfile_builder_image_based }}"

# Container variables
ENV OPERATOR_VERSION="{{ operator_version }}"

# Install Operator SDK
COPY --from=quay.io/operator-framework/operator-sdk:v{{ operator_version }} /usr/local/bin/operator-sdk /usr/local/bin/operator-sdk

# Install Ansible Operator
COPY --from=quay.io/operator-framework/ansible-operator:v{{ operator_version }} /usr/local/bin/ansible-operator /usr/local/bin/ansible-operator

# Container variables
ENV KUSTOMIZE_VERSION="{{ kustomize_version }}"

# Install kustomize
RUN echo "Installing kustomize version: ${KUSTOMIZE_VERSION}..."  && \
    curl -sSLo - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_$(uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/').tar.gz | tar xzf - -C /usr/local/bin/

# Container variables
ENV KUBECTL_VERSION="{{ kubectl_version }}"

# Install kubectl.
RUN echo "Installing kubectl version: ${KUBECTL_VERSION}..."  && \
    curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/$(uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/')/kubectl -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

# Install requirements.
RUN echo "Installing operator sdk version: ${OPERATOR_VERSION}..."  && \
    curl -L https://raw.githubusercontent.com/operator-framework/ansible-operator-plugins/v${OPERATOR_VERSION}/testdata/memcached-molecule-operator/requirements.yml -o /tmp/requirements.yml && \
    ansible-galaxy collection install -r /tmp/requirements.yml -p /usr/share/ansible/collections && \
    rm -f /tmp/requirements.yml

CMD [ "/bin/bash" ]

# Labels
LABEL name="${IMAGE_NAME}" \
      summary="${IMAGE_SUMMARY}" \
      maintainer="{{ dockerfile_builder_image_authors }}" \
      description="${IMAGE_DESCRIPTION}" \
      org.opencontainers.image.title="${IMAGE_TITLE}" \
      org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.description="${IMAGE_DESCRIPTION}" \
      io.k8s.description="${IMAGE_DESCRIPTION}" \
      io.k8s.display-name="${IMAGE_TITLE}" \
      io.openshift.tags="${IMAGE_NAME},{{ dockerfile_builder_image_ocp_tags }}"
