# image
version_image_suffix: nginx
image_from_ctr: "nginx{{ nginx_version | replace('.','') }}"
image_tag_from_ctr: "{{ nginx_version }}"
dockerfile_builder_image_from_repo_name: nginx
dockerfile_builder_image_ocp_tags_list:
  - ${IMAGE_NAME}
  - nginx
  - nginx-{{ nginx_version | replace('.','') }}
  - nginx{{ nginx_version | replace('.','') }}
  - moodle
  - moodle{{ moodle_version | replace('.','') }}
  - moodle-{{ moodle_version | replace('.','') }}
dockerfile_builder_image_ocp_tags: "{{ dockerfile_builder_image_ocp_tags_list | join(',') }}"

# source dir
template_path: "{{ template_dir }}/moodle_nginx"
