# {{ ansible_managed  }}
ARG ARG_IMAGE_FROM={{ dockerfile_builder_image_from }}
FROM ${ARG_IMAGE_FROM}

# General variables
ENV IMAGE_NAME={{ dockerfile_builder_image_name }} \
    IMAGE_SUMMARY="Nodejs {{ node_version }} image based on {{ dockerfile_builder_image_based }} for Continuous Integration (CI)" \
    IMAGE_DESCRIPTION="{{ dockerfile_builder_image_based }} based image with node {{ node_version }} javascript runtime for CI" \
    IMAGE_TITLE="Node image based on {{ dockerfile_builder_image_based }} for CI"

USER 0

RUN install-pkgs make git curl tar xz unzip procps-ng
RUN npm i -g @nestjs/cli@10; npm cache clean --force; rm -rf ~/.npm

# Labels
LABEL name="${IMAGE_NAME}" \
    summary="${IMAGE_SUMMARY}" \
    maintainer="{{ dockerfile_builder_image_authors }}" \
    description="${IMAGE_DESCRIPTION}" \
    org.opencontainers.image.title="${IMAGE_TITLE}" \
    org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
    org.opencontainers.image.description="${IMAGE_DESCRIPTION}" \
    io.k8s.description="${IMAGE_DESCRIPTION}" \
    io.k8s.display-name="${IMAGE_TITLE}" \
    io.openshift.tags="${IMAGE_NAME},{{ dockerfile_builder_image_ocp_tags }}"
