# origin
origin_name: gitlab.com
origin_project: krestomatio/m4e

# registry
registry_name: quay.io
registry_project: krestomatio

# platform vars
centos_version: '8'
php_version: '7.2'
httpd_version: '2.4'
nginx_version: '1.14'
postgres_version: '10'
postgres_prev_version: '9.6'
moodle_version: '3.9'

# builder
# dockerfile_builder_push: true
dockerfile_builder_image_pkgs_mgm: microdnf --setopt=tsflags=nodocs -y
dockerfile_builder_image_timezone: America/Costa_Rica
dockerfile_builder_image_authors: Job Céspedes Ortiz <jobcespedes@gmail.com>

# moodle
moodle_git_branch: "MOODLE_{{ moodle_version | replace('.','') }}_STABLE"
moodle_git_ref: "{{ lookup('url', dockerfile_builder_image_git_chk) }}"
moodle_git_commit: "{{ moodle_git_ref.object.sha }}"

dockerfile_builder_image_git_remote: "git://github.com/moodle/moodle"
dockerfile_builder_image_git_chk:
  "{{ 'https://api.github.com/repos/moodle/moodle/git/refs/heads/' +
  moodle_git_branch }}"
