#!/bin/bash -e
# description: additional entrypoint script for moodle php-fpm

# Copy moodle config.php if variable $MOODLE_CONFIG_DIR is set and file does not exist in $MOODLE_APP
if ! [ -z ${MOODLE_CONFIG_DIR+x} ] && [ -f ${MOODLE_CONFIG_DIR}/config.php ] && ! [ -f ${MOODLE_APP}/config.php ] ; then
    cp -L ${MOODLE_CONFIG_DIR}/config.php ${MOODLE_APP}/config.php
    chmod 0660 ${MOODLE_APP}/config.php
fi
