# dockerfile_builder
container_builder_image_from: false
dockerfile_builder_excluded_files:
  - pkg_list_linux_*

# ci
prepare_image_task: centos-minimal

# other
version_release_no_bump: true
ctr_readme_section: |-
  This is a {{ dockerfile_builder_image_title }}, similar to Fedora-minimal or UBI.

  ## How image is built?
  ```bash
  docker build . -t "{{ container_image }}"
  ```
