# ci
prepare_image_task: centos8

# prepare
centos8_build_kickstart: "{{ ansible_host }}.ks"
centos8_build_rootfs: "{{ ansible_host }}.tar.xz"

# other
version_release_no_bump: true
ctr_readme_section: |-
  This is a {{ dockerfile_builder_image_title }}, similar to Fedora-minimal or UBI.

  ## How image is built?
  ```bash
  docker build . -t "{{ container_image }}"
  ```
