# {{ ansible_managed  }}
{% if moodle_app_copy_from is defined %}
FROM {{ moodle_app_copy_from }} AS app
RUN app-git -a -e '.git*'

{% endif %}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_version="{{ dockerfile_builder_image_version }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    MOODLE_version="{{ moodle_version }}" \
    MOODLE_ver_short="{{ moodle_version | replace('.','') }}" \
    MOODLE_commit="{{ moodle_git_commit }}" \
    TZ="{{ dockerfile_builder_image_timezone }}"

# General variables
ENV IMAGE_name=moodle_php-fpm \
    IMAGE_summary="PHP $PHP_version for Moodle" \
    IMAGE_description="This ${IMAGE_based} based container image runs PHP ${PHP_version} for Moodle" \
    IMAGE_title="PHP ${PHP_version} for Moodle"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.version="${IMAGE_version}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},php,php-fpm,php${PHP_ver_short},php-${PHP_ver_short},moodle,moodle${MOODLE_ver_short},moodle-${MOODLE_ver_short}"

# Component bash variables
ENV MOODLE_app=${HTTPD_public_path} \
    MOODLE_data=/var/moodledata

# php-curl included in php-common
# php-zip as php-pecl-zip
# php-xsl as php-xml
# php-fpm php-cli php-opcache already installed in base image
ENV OS_install_pkgs="php-gd php-intl php-ldap \
                  php-pgsql php-soap php-xmlrpc  \
                  php-xml php-pecl-zip php-mbstring \
                  php-json"

USER 0

COPY conf/usr/bin/* /usr/bin/
COPY conf/usr/libexec/* /usr/libexec/

RUN container-setup
RUN install-pkgs ${OS_install_pkgs}

{% if moodle_app_copy_from is defined %}
COPY --from=app {{ moodle_code_copy_path | default('/var/www/html') }} {{ moodle_code_copy_dest | default('/var/www/html') }}

{% endif %}
RUN container-setup-php-moodle

USER ${CTR_user_id}
