- hosts: "{{ build_containers | default('all') }}"
  connection: local
  serial: "{{ omit if build_playbook_no_serial else 1 }}"
  diff: "{{ build_play_diff | default(false) }}"
  vars_files: "vars/build.yml"
  tasks:
    - name: include cloud provider vars
      vars:
        cloud_provider: "{{ lookup('env','CLOUD_PROVIDER') | default('none',true) }}"
      when:
        - cloud_provider == 'gke'
      include_vars:
        dir: "vars/{{ cloud_provider }}/"
        ignore_unknown_extensions: True
        extensions:
          - yml

    - include_tasks: tasks/registry.yml

    - include_tasks: tasks/cache.yml

    - include_tasks: tasks/centos8-minimal.yml

    - name: build containers
      when: not dockerfile_builder_omit | default(false)
      include_role:
        name: dockerfile_builder

    - include_tasks: tasks/tags.yml
      loop: "{{ dockerfile_builder_tags }}"
      loop_control:
        loop_var: tag
      when:
        - tag is defined and tag
