- hosts: localhost
  tasks:
    - name: build containers
      vars:
        dockerfile_builder_image_from: "{{ item.image_from }}"
        dockerfile_builder_image: "{{ item.image }}"
        dockerfile_builder_image_pull: "{{ item.pull | default(image_pull) }}"
        dockerfile_builder_image_version:
          "{{ item.image_version | default(false) }}"
      include_role:
        name: dockerfile_builder
      loop: "{{ dockerfile_builder_images }}"
