- hosts: localhost
  tasks:
    - name: build containers
      vars:
        dockerfile_builder_image: "{{ item }}"
      include_role:
        name: dockerfile_builder
      loop: "{{ containers_to_build }}"
