- hosts: "{{ ctrs_to_build | default('all') }}"
  connection: local
  tasks:
    - name: set created time
      when: dockerfile_builder_image_created is not defined
      run_once: true
      set_fact:
        dockerfile_builder_image_created: "{{ ansible_date_time.iso8601 }}"


- hosts: "{{ ctrs_to_build | default('all') }}"
  connection: local
  serial: "{{ omit if dockerfile_builder != 'podman' or dockerfile_builder != 'docker' }}"
  tasks:
    - name: build containers
      import_role:
        name: dockerfile_builder
