- name: release
  hosts: "{{ play_containers | default('all') }}"
  connection: local
  any_errors_fatal: "{{ play_any_errors_fatal }}"
  diff: "{{ play_diff | default(omit) }}"
  vars_files: "vars/ci.yml"
  environment:
    DOCKER_BUILDKIT: 1
  tasks:
    - name: include variables
      include_tasks: tasks/pipeline/include-vars.yml

    - name: skip if no artifact commit tag
      when: not artifact_tag
      set_fact:
        skip_ci: true
        skip_end_msg: "commit is not from a pull request, skipping '{{ ansible_play_name }}' playbook"

    - name: include skip-ci
      include_tasks: tasks/pipeline/skip-ci.yml
      run_once: true

    - name: check valid builder
      tags: always
      run_once: true
      assert:
        that: dockerfile_builder in ['docker','podman']

    - name: git related config
      include_tasks: "tasks/git/config.yml"
      run_once: true

    - name: builder related config
      include_tasks: "tasks/config/{{ dockerfile_builder }}.yml"
      when: builder_config | default(false) | bool
      run_once: true

    - name: set image version related facts
      include_tasks: tasks/builder/version.yml

    - name: "download artifacts"
      vars:
        artifact_name: "{{ item.name }}"
        artifact_archive: "{{ item.archive }}"
        artifact_path: "{{ item.path }}"
      loop: "{{ artifacts }}"
      include_tasks: tasks/artifact/download.yml
      run_once: true

    - name: load image state
      include_tasks: tasks/state/load.yml

    - name: end playbook for this host
      include: tasks/pipeline/end_host.yml

    - name: promote image
      include_tasks: tasks/promote/copy.yml

    - name: save image state
      include_tasks: tasks/state/save.yml

    - name: release
      run_once: true
      block:
      - name: set release version
        set_fact:
          release_version: ""

      - name: add changes
        include_tasks: tasks/git/add.yml

      - name: commit changes
        include_tasks: tasks/git/commit.yml

      - name: tag version
        include_tasks: tasks/git/tag.yml

      - name: push changes
        include_tasks: tasks/git/push.yml
