#!/bin/bash -e
# description: additional entrypoint script for nfs ganesha

# Configure defaults
if [ -z "${NFS_GANESHA_CONF_NO_OVERWRITE:-}" ] ; then
    cat << _EOF > "${NFS_GANESHA_CONF_FILE}"
NFS_CORE_PARAM {
    Protocols = 4;
    NFS_Port = ${NFS_GANESHA_PORT};
    Rquota_Port = ${NFS_GANESHA_RQUOTA_PORT};
    fsid_device = true;
}
EXPORT_DEFAULTS {
    SecType = sys;
}
%include "${NFS_GANESHA_CONF_EXTRA_FILE}"
_EOF

    cat << _EOF > "${NFS_GANESHA_CONF_EXTRA_FILE}"
NFSv4 {
    Grace_Period = ${NFS_GANESHA_GRACE_PERIOD};
}
MDCACHE {
    Entries_HWMark = ${NFS_GANESHA_EXPORT_HWMARK};
}
EXPORT {
    Export_Id = ${NFS_GANESHA_EXPORT_ID};
    Path = "${NFS_GANESHA_EXPORT_DIR}";
    Pseudo = /;
    Access_Type = RW;
    Squash = ${NFS_GANESHA_EXPORT_SQUASH};
    FSAL {
        Name = VFS;
    }
}
LOG {
    COMPONENTS {
        ALL = ${NFS_GANESHA_LOG_LEVEL};
    }
}
_EOF
fi

# dbus
if [ -S '${DBUS_RUN_DIR}/system_bus_socket' ]; then
    echo "system dbus already running..."
else
    if [ "${DBUS_RUN_WAIT,,}" == "true" ]; then
        echo "waiting for system dbus..."
        timeout 10 bash -c "while ! [ -S '${DBUS_RUN_DIR}/system_bus_socket' ]; do sleep 1; done" || echo "timeout waiting for system dbus"
    else
        echo "starting system dbus..."
        systemd-tmpfiles --create /usr/lib/tmpfiles.d/dbus.conf
        dbus-uuidgen --ensure
        dbus-daemon --fork --nopidfile --system
    fi
fi
