FROM scratch

# General variables
ENV IMAGE_ROOTFS_PKGS_CHECKSUM="{{ dockerfile_builder_image_pkgs_checksum }}"

ADD rocky8-minimal.tar.xz /

# Labels
LABEL org.opencontainers.image.title="Rocky Linux Minimal Image" \
      org.opencontainers.image.licenses="GPLv2"

CMD ["/bin/bash"]
