# image
dockerfile_builder_image_from: "{{ registry_path }}/httpd{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
