- name: build using cache from images
  when:
    - dockerfile_builder_cache_from_tags is defined and dockerfile_builder_cache_from_tags
    - dockerfile_builder_cache_from is not defined
  set_fact:
    cache_from: true

- when:
    - cache_from | default(false)
  block:
  - name: set images and respective tags (if any)
    when: item is defined and item
    with_items: "{{ (dockerfile_builder_cache_from_tags |
      default(dockerfile_builder_tag) | default('latest')) }}"
    set_fact:
      dockerfile_builder_cache_from:
        "{{ dockerfile_builder_cache_from | default([]) +
        [dockerfile_builder_image + ':' + item] }}"

  - name: set cache build args variables
    when: dockerfile_builder == 'docker'
    set_fact:
      dockerfile_builder_args: "{{  dockerfile_builder_args | default({}) | combine({'BUILDKIT_INLINE_CACHE': 1}) }}"

  - name: pull cache image using docker
    ignore_errors: true
    changed_when: false
    with_items: "{{ dockerfile_builder_cache_from }}"
    when: dockerfile_builder == 'docker'
    docker_image:
      name: "{{ item }}"
      source: pull

  - name: pull cache image using podman
    ignore_errors: true
    changed_when: false
    with_items: "{{ dockerfile_builder_cache_from }}"
    when: dockerfile_builder == 'podman'
    podman_image:
      name: "{{ item }}"
      validate_certs:
        "{{ dockerfile_builder_validate_certs | default(omit) }}"
