- name: include cloud provider vars
  when:
    - cloud_provider | default('none') != 'none'
    - cloud_provider in cloud_providers
  include_vars:
    file: "{{ playbook_dir }}/vars/provider/{{ cloud_provider }}.yml"
