- name: check state related vars dir exists
  stat:
    path: "{{ playbook_dir }}/vars/state"
  register: state_vars_dest_check

- name: create state related vars dir
  when:
    - not ansible_check_mode
    - not state_vars_dest_check.stat.exists
  file:
    dest: "{{ playbook_dir }}/vars/state"
    state: directory
    mode: '0755'

- name: save state related vars
  when:
    - state_vars_save | default(true)
    - state_yml_tag is defined and state_yml_tag
    - state_yml_id is defined and state_yml_id
    - state_yml_repo_digest is defined and state_yml_repo_digest
    - not ansible_check_mode
  template:
    src: state.yml.j2
    dest: "{{ playbook_dir }}/vars/state/{{ ansible_host }}.yml"
    mode: '0644'

- name: include state related vars
  when:
    - state_vars_load | default(true)
    - state_vars_dest_check.stat.exists
  include_vars:
    dir: "{{ playbook_dir }}/vars/state"
    ignore_unknown_extensions: True
    extensions:
      - yml
