- name: get version based on git tag
  vars:
    version_image_bump: ''
  when:
    - version_git_based | default(false)
  block:
    - name: set image version
      when: version_image is not defined
      set_fact:
        version_image:  "{{ lookup('git_semver', playbook_dir, bump=version_image_bump,
          want='dict') }}"

    - name: set major version
      when: version_image_major is not defined
      set_fact:
        version_image_major: "{{ version_image.major }}"

    - name: set minor version
      when: version_image_minor is not defined
      set_fact:
        version_image_minor: "{{ version_image.minor }}"

    - name: set full version
      when: version_image_full is not defined
      set_fact:
        version_image_full:
          "{{ version_image.full + ( '' if
          version_default_suffix is not defined or
          version_image.prerelease or version_image.build
          else version_default_suffix )  }}"

- name: state image tag
  set_fact:
    state_yml_tag: "{{ version_image_full }}"

- name: set container image version
  when:
    dockerfile_builder_image_version is not defined and
    dockerfile_builder_image_version
  set_fact:
    dockerfile_builder_image_version: "{{ version_image_full }}"

- name: set container image tag based on full version
  set_fact:
    dockerfile_builder_tags: "{{ dockerfile_builder_tags | default([])
      + [version_image_full] }}"

- name: set container image fallback tags based on branch and commit of version tag
  set_fact:
    dockerfile_builder_tags: "{{ dockerfile_builder_tags | default([])
      + [version_image.commit] + [version_image.branch] }}"

- name: set container image tags based on major and minor version
  when: version_include_major_minor_tags | default(false)
  set_fact:
    dockerfile_builder_tags: "{{ dockerfile_builder_tags | default([])
      + [version_image_major + '.' + version_image_minor]
      + [version_image_major] }}"
