- name: get version based on git tag
  vars:
    version_image_bump: patch
  when:
    - version_git_based | default(false)
  block:
    - name: set image version
      when: version_image is not defined
      set_fact:
        version_image:  "{{ lookup('git_semver', playbook_dir, bump=version_image_bump,
          want='dict') }}"

    - name: set major version
      when: version_image_major is not defined
      set_fact:
        version_image_major: "{{ version_image.major }}"

    - name: set minor version
      when: version_image_minor is not defined
      set_fact:
        version_image_minor: "{{ version_image.minor }}"

    - name: set full version
      when: version_image_full is not defined and not version_image_full
      block:
        - name: set full version
          set_fact:
            version_image_full: "{{ version_image.full  }}"

        - name: add build version
          vars:
            version_add_build_suffix_build_var: BUILD_ID
            version_add_build_suffix_branch_var: BRANCH_NAME
            version_add_build_suffix: "{{ '-SNAPSHOT-' + lookup('env',version_add_build_suffix_branch_var) |
              default('PR1',true) + '-' + lookup('env',version_add_build_suffix_build_var) | default('1',true)  }}"
          when:
            - version_add_build | default(false)
            - not version_image.prerelease
            - not version_image.build
          set_fact:
            version_image_full:
              "{{ version_image.full + version_add_build_suffix  }}"

- name: state image tag
  set_fact:
    state_yml_tag: "{{ version_image_full }}"

- name: set container image version
  when:
    dockerfile_builder_image_version is not defined and
    dockerfile_builder_image_version
  set_fact:
    dockerfile_builder_image_version: "{{ version_image_full }}"

- name: set container image tag based on full version
  set_fact:
    dockerfile_builder_tags: "{{ dockerfile_builder_tags | default([])
      + [version_image_full] }}"

- name: set container image fallback tags based on branch and commit of version tag
  when: version_include_fallback_tags | default(false)
  set_fact:
    dockerfile_builder_tags: "{{ dockerfile_builder_tags | default([])
      + [version_image.commit] + [version_image.branch] }}"

- name: set container image tags based on major and minor version
  when:
    - version_include_major_minor_tags | default(false)
  set_fact:
    dockerfile_builder_tags: "{{ dockerfile_builder_tags | default([])
      + [version_image_major + '.' + version_image_minor]
      + [version_image_major] }}"
