# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_authors="{{ dockerfile_builder_image_authors }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    IMAGE_based="{{ dockerfile_builder_image_based }}" \
    IMAGE_ocp_tags="{{ dockerfile_builder_image_ocp_tags }}" \
    CTR_pkg_mgm="{{ dockerfile_builder_image_pkgs_mgm }}"

# General variables
ENV IMAGE_name=base \
    IMAGE_summary="${IMAGE_based} based image" \
    IMAGE_description="${IMAGE_based} based for building other images" \
    IMAGE_title="${IMAGE_based} based image"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="${IMAGE_authors}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},${IMAGE_ocp_tags}" \
      maintainer="${IMAGE_authors}"

# Container variables
ENV CTR_user=default \
    CTR_user_id="1001" \
    CTR_user_gecos="Default Application User" \
    CTR_group=root \
    CTR_group_id="0" \
    CTR_app="/opt/default" \
    CTR_entrypoint_opt_path=/opt/container-entrypoint.d

ENV OS_install_pkgs="findutils gzip platform-python"

# https://github.com/rpm-software-management/microdnf/issues/50
RUN mkdir -p /run/user/$(id -u)

COPY conf/usr/bin/* /usr/bin/
COPY conf/container-entrypoint.d/* ${CTR_entrypoint_opt_path}/

RUN container-setup
RUN install-pkgs ${OS_install_pkgs}

ENTRYPOINT ["container-entrypoint"]
