  - name: check for [skip.ci] in commit message
    changed_when: false
    register: skip_ci_check
    shell: git log -1 --pretty=%B | cat

  - name: "check for [skip.ci.{{ ansible_play_name }}] in commit message"
    changed_when: false
    register: skip_ci_playbook_check
    shell: git log -1 --pretty=%B | cat

  - name: set skip fact based on environment variable
    when: lookup('env','SKIP_CI_'+ ansible_play_name | upper ) | default(lookup('env','SKIP_CI'),true)
      | default(false,true)
    set_fact:
      skip_ci: true

  - name: set skip fact based on commit message
    when:
      - skip_ci_check.stdout is defined or skip_ci_playbook_check.stdout is defined
      - "'[skip.ci]' in skip_ci_check.stdout or
        ('[skip.ci.' + ansible_play_name + ']') in skip_ci_playbook_check.stdout"
    set_fact:
      skip_ci: true

  - name: end playbook
    when: skip_ci | default(false)
    block:
    - name: end playbook when skip is set
      vars:
        skip_end_msg: "skip was set, {{ ansible_play_name }} ending playbook"
      debug:
        msg: "{{ skip_end_msg }}"

    - meta: end_play
