# image
dockerfile_builder_image_from: "{{ dest_subdir }}/moodle_nginx_web"
dockerfile_builder_image_version: "0.0.1"

# source dir
src_path: "{{ src_dir }}/{{ src_subdir }}/moodle_php-fpm"

# other
moodle_app_copy_from: "{{ registry_name }}/{{ registry_project }}/moodle_app:latest"
