centos_version: 10
image_from_ctr: "centos{{ centos_version }}-base"
image_tag_from_ctr: "{{ centos_version }}-base"
dockerfile_builder_image_from_repo_name: centos
dockerfile_builder_image_based: "CentOS {{ centos_version }} Stream minimal"
