# platform vars
image_ansible_version: '2.9.*'
molecule_version: '3.1.*'
docker_version: 'stable-dind'

# registry
registry_name: "{{ ci_registry_name }}"

# ci
prepare_image_task: ansible-ci

# jx
# jx3_version_install: true
# jx3_version_url: https://github.com/jenkins-x/jx-cli/releases/latest
# jx3_version_regex: '(?<=[\/v|\/])([0-9]+)\.([0-9]+)\.([0-9]+)'
# jx2_version_install: true
# jx2_version_url: https://github.com/jenkins-x/jx/releases/latest
# jx2_version_regex: '(?<=[\/v|\/])([0-9]+)\.([0-9]+)\.([0-9]+)'

# oras
oras_version_install: true
oras_version_url: https://github.com/deislabs/oras/releases/latest
oras_version_regex: '(?<=[\/v|\/])([0-9]+)\.([0-9]+)\.([0-9]+)'
