# image
dockerfile_builder_image_from: "{{ registry_path }}/moodle_nginx_web{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_name: moodle_nginx_web
dockerfile_builder_image_summary: "PHP $PHP_version and NGINX ${NGINX_version} for Moodle"
dockerfile_builder_image_description: "This {{ dockerfile_builder_image_based }} based container image runs PHP ${PHP_version} and NGINX ${NGINX_version} for Moodle"
dockerfile_builder_image_title: "PHP ${PHP_version} and NGINX ${NGINX_version} for Moodle"
dockerfile_builder_image_oc_tags:
  "{{ '${IMAGE_name},php,php-fpm,php${PHP_ver_short},php-${PHP_ver_short}'
  + ',nginx,nginx-${NGINX_ver_short},nginx${NGINX_ver_short}'
  + ',moodle,moodle${MOODLE_ver_short},moodle-${MOODLE_ver_short}' }}"

# source dir
template_path: "{{ template_dir }}/moodle_php-fpm"

# other
moodle_app_copy_from: "{{ registry_path }}/moodle_app{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
alternative_version_full: "{{ moodle_git_source_version }}"
alternative_version_full_add_build: true
