# image
dockerfile_builder_image_from: "{{ registry_path }}/moodle_nginx_web{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_name: moodle_nginx_web
dockerfile_builder_image_summary: "PHP $PHP_VERSION and NGINX ${NGINX_VERSION} for Moodle"
dockerfile_builder_image_description: "This {{ dockerfile_builder_image_based }} based container image runs PHP ${PHP_VERSION} and NGINX ${NGINX_VERSION} for Moodle"
dockerfile_builder_image_title: "PHP ${PHP_VERSION} and NGINX ${NGINX_VERSION} for Moodle"
dockerfile_builder_image_oc_tags:
  "{{ '${IMAGE_NAME},php,php-fpm,php${PHP_VER_SHORT},php-${PHP_VER_SHORT}'
  + ',nginx,nginx-${NGINX_VER_SHORT},nginx${NGINX_VER_SHORT}'
  + ',moodle,moodle${MOODLE_VER_SHORT},moodle-${MOODLE_VER_SHORT}' }}"

# source dir
template_path: "{{ template_dir }}/moodle_php-fpm"

# ci
prepare_image_task: moodle

# other
moodle_app_copy_from: "{{ registry_path }}/moodle_app{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
