{% set version = '7.0.31-fpm-stretch' %}
{% set zend_extension = '7.0.31-fpm-stretch' %}
{% set moodle_branch = 'MOODLE_35_STABLE' %}
# {{ ansible_managed  }}

# first stage
FROM php:{{ version }} AS build

# Build dependencies
# https://docs.moodle.org/35/en/PHP
RUN apt-get update && \
    apt-get install -y --no-install-recommends libxml2-dev zlib1g-dev libpng-dev \
        libfreetype6-dev libjpeg62-turbo-dev libicu-dev libpq-dev libldap2-dev libxslt-dev && \
    docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ && \
    docker-php-ext-install gd && \
    docker-php-ext-configure xmlrpc --with-libxml-dir=/usr/include/ && \
    docker-php-ext-install xmlrpc && \
    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu && \
    docker-php-ext-install ldap && \
    # Already installed: curl iconv mbstring openssl tokenizer
    # ctype simplexml spl pcre dom xml json
    docker-php-ext-install soap zip intl pgsql xsl && \
    docker-php-ext-configure opcache --enable-opcache && \
    docker-php-ext-install opcache && \
    docker-php-source delete && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/*

# second stage
FROM php:{{ version }} AS source

# Install git and rsync
RUN apt-get update && \
    apt-get install -y --no-install-recommends git rsync && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/*

# get source code
RUN {{ dockerfile_builder_get_src_cmd | default('git clone --branch ' + moodle_branch + ' --depth 1 git://github.com/moodle/moodle /var/www/repo') }}

Add {{ dockerfile_builder_chk_src_url | default('https://api.github.com/repos/moodle/moodle/git/refs/heads/' + moodle_branch) }} /tmp/version.json

RUN cd /var/www/repo && {{ dockerfile_builder_pull_src | default('git pull origin ' + moodle_branch) }} && \
    rsync -a --exclude=.git* --filter='dir-merge,- .gitignore' \
    /var/www/repo/ /var/www/source/

# third stage
FROM php:{{ version }}

LABEL \
{% if dockerfile_builder_image_created is defined %}
  {{ dockerfile_builder_image_created }} \
{% endif %}
{% if dockerfile_builder_image_revision is defined %}
  {{ dockerfile_builder_image_revision }} \
{% endif %}
  org.opencontainers.image.title="PHP-FPM for Moodle" \
  org.opencontainers.image.authors="Job Céspedes Ortiz <jobcespedes@gmail.com>" \
  org.opencontainers.image.description="This debian9 based docker image runs php-fpm for moodle usage" \
  org.opencontainers.image.version="{{ version }}"

ARG DOCUMENT_ROOT=/var/www/html
ARG MY_TZ=America/Costa_Rica

ENV WEB_DOCUMENT_ROOT=$DOCUMENT_ROOT
ENV TZ=$MY_TZ

# Copy lib
COPY --from=build --chown=0:0 /usr/lib/x86_64-linux-gnu/libpng16.so.16 /usr/lib/x86_64-linux-gnu/libpng16.so.16
COPY --from=build --chown=0:0 /usr/lib/x86_64-linux-gnu/libjpeg.so.62 /usr/lib/x86_64-linux-gnu/libjpeg.so.62
COPY --from=build --chown=0:0 /usr/lib/x86_64-linux-gnu/libfreetype.so.6 /usr/lib/x86_64-linux-gnu/libfreetype.so.6
COPY --from=build --chown=0:0 /usr/lib/x86_64-linux-gnu/libpq.so.5 /usr/lib/x86_64-linux-gnu/libpq.so.5
COPY --from=build --chown=0:0 /usr/lib/x86_64-linux-gnu/libexslt.so.0 /usr/lib/x86_64-linux-gnu/libexslt.so.0
COPY --from=build --chown=0:0 /usr/lib/x86_64-linux-gnu/libxslt.so.1 /usr/lib/x86_64-linux-gnu/libxslt.so.1

# Copy php extensions and config
COPY --from=build --chown=0:50 /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=build --chown=0:50 /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/

# Copy php config
COPY --chown=0:50  conf/custom-php.ini /usr/local/etc/php/conf.d/php.ini
COPY --chown=0:50 conf/custom-opcache.ini /usr/local/etc/php/conf.d/opcache.ini
COPY --chown=0:50 conf/php-fpm-entrypoint.sh /usr/local/bin/php-fpm-entrypoint

# Copy source code
COPY --from=source --chown=33:33 /var/www/source/ /var/www/html/

WORKDIR ${WEB_DOCUMENT_ROOT}

EXPOSE 9000

ENTRYPOINT ["php-fpm-entrypoint"]

CMD ["php-fpm"]
