# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General variables
ENV IMAGE_name=rootfs-creator \
    IMAGE_summary="{{ dockerfile_builder_image_based }} based image" \
    IMAGE_description="{{ dockerfile_builder_image_based }} based for building rootfs" \
    IMAGE_title="{{ dockerfile_builder_image_based }} based image"

# Container variables
ENV CTR_working_dir=/build

RUN dnf install -y anaconda-tui lorax jq
RUN mkdir $CTR_working_dir

COPY conf/usr/bin/* /usr/bin/

WORKDIR $CTR_working_dir

ENTRYPOINT ["/usr/bin/rootfs-creator"]

# Labels
LABEL name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      maintainer="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},{{ dockerfile_builder_image_ocp_tags }}"
