# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_authors="{{ dockerfile_builder_image_authors }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    IMAGE_based="{{ dockerfile_builder_image_based }}" \
    IMAGE_ocp_tags="{{ dockerfile_builder_image_ocp_tags }}"

# General variables
ENV IMAGE_name=rootfs-creator \
    IMAGE_summary="${IMAGE_based} based image" \
    IMAGE_description="${IMAGE_based} based for building rootfs" \
    IMAGE_title="${IMAGE_based} based image"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="${IMAGE_authors}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},${IMAGE_ocp_tags}" \
      maintainer="${IMAGE_authors}"

# Container variables
ENV CTR_working_dir=/build

RUN dnf install -y anaconda-tui lorax
RUN mkdir $CTR_working_dir

COPY conf/usr/bin/* /usr/bin/

WORKDIR $CTR_working_dir

ENTRYPOINT ["/usr/bin/build-rootfs"]
