#!/bin/bash -e
# description: additional entrypoint script for php-fpm

# Exit if nginx is installed and php-fpm conf file not writable
if rpm -q nginx &>/dev/null; then
    if ! [ -w "${PHP_FPM_CONF_FILE}" ]; then
        echo "Nginx installed and ${PHP_FPM_CONF_FILE} not writable...doing nothing here"
        exit 0
    fi
fi

# listen.allowed_clients with values 'empty' or 'any' does not  work
# so it is remove in that case
if [ ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} != '127.0.0.1' ]; then
    if [[ -z ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} || ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} == 'any' ]]; then
        sed -i "s@^listen.allowed_clients@; listen.allowed_clients@" ${PHP_FPM_POOL_FILE}
    else
        sed -i 's@^listen.allowed_clients.*@listen.allowed_clients = ${PHP_FPM_LISTEN_ALLOWED_CLIENTS}@' ${PHP_FPM_POOL_FILE}
    fi
fi
