#! /bin/bash -u
# description: check moodle php-fpm container

usage() {
    cat 1>&2 <<EOF
Script to check moodle php container.

ENVIRONMENT VARS:
PHP_FPM_port            tcp port php-fpm listen to
MOODLE_app              path to moodle code
MOODLE_data             moodledata path

USAGE:
    check-container [OPTIONS]

OPTIONS (check moodle php container):
  -t            check php-fpm tcp port (if not using unix socket)
  -c            check if config.php exists
  -d            check if database is installed
  -u            check if upgrade not needed
  -m            check if moodledata is writable
  -l            check liveness (-d -m) (Default)
  -r            check readiness (-c -d -m)

EXAMPLES:
    check-container -i
    check-container -u
    check-container -r
EOF
}

check_tcp_port() {
    # check php-fpm tcp port

    # Check php-fpm is not using unix socket
    if [[ ${PHP_FPM_listen+x} != /* ]]; then
        cat < /dev/null > /dev/tcp/127.0.0.1/${PHP_FPM_port}
    else
        echo "$0: CHECK: php-fpm is using unix socket"
    fi
}

check_config_file() {
    # check config.php exists and its sintax
    test -f ${MOODLE_app}/config.php
    if [ $? -ne 0 ]; then
        echo "$0: CHECK: config.php does not exist"
        exit 1
    fi
    php -l ${MOODLE_app}/config.php
    if [ $? -ne 0 ]; then
        echo "$0: CHECK: config.php sintax error"
        exit 1
    fi
}

check_database_installed() {
    # check database is installed
    # code exit 2 means database scheme not installed
    set -e
    php <<CODE
<?php
define('CLI_SCRIPT', true);
require('${MOODLE_app}/config.php');
if (empty(\$CFG->version)) {
    echo "CHECK: Database is not yet installed\n";
    exit(2);
}
?>
CODE
}

check_upgrade_not_pending() {
    # it clears cache
    # not intended to run too frequently
    # code exit 2 means upgrade pending
    set -e
    php <<CODE
<?php
if (function_exists('opcache_reset') and !isset(\$_SERVER['REMOTE_ADDR'])) {
    opcache_reset();
}

define('CLI_SCRIPT', true);
define('CACHE_DISABLE_ALL', true);

require('${MOODLE_app}/config.php');
if (moodle_needs_upgrading()) {
    echo "CHECK: Moodle upgrade needed\n";
    exit(2);
}
?>
CODE
}

check_moodledata() {
    # check moodledata is writable
    TMPFILE=`mktemp -q -p ${MOODLE_data}/`
    if [ $? -ne 0 ]; then
        echo "$0: CHECK: Can't create file in '${MOODLE_data}'"
        exit 1
    fi
    rm $TMPFILE
}

while getopts ":tcdumlr" opt; do
  case ${opt} in
    t )
        check_tcp_port
        ;;
    c )
        check_config_file
        ;;
    d )
        check_database_installed
        ;;
    u )
        check_upgrade_not_pending
        ;;
    m )
        check_moodledata
        ;;
    l )
        check_database_installed
        check_moodledata
        ;;
    r )
        check_config_file
        check_database_installed
        check_moodledata
        ;;
    \? )
        usage
        exit
        ;;
  esac
done
shift $((OPTIND -1))

if (( $OPTIND == 1 )); then
    echo -e "No check. Use an option:\n"
    usage
    exit
fi
