# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_authors="{{ dockerfile_builder_image_authors }}" \
    IMAGE_version="{{ dockerfile_builder_image_version }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    HTTPD_version="{{ httpd_version }}" \
    HTTPD_ver_short="{{ httpd_version | replace('.','') }}"

# General variables
ENV IMAGE_name=httpd \
    IMAGE_summary="Apache2 $HTTPD_version" \
    IMAGE_description="This ${IMAGE_based} based container image runs Apache ${HTTPD_version}" \
    IMAGE_title="Apache ${HTTPD_version}" \
    IMAGE_service_port="8080" \
    IMAGE_service_name="http"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="${IMAGE_authors}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.version="${IMAGE_version}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.expose-services="${IMAGE_service_port}:${IMAGE_service_name}" \
      io.openshift.tags="${IMAGE_name},apache,apache-${HTTPD_ver_short},apache${HTTPD_ver_short}" \
      maintainer="${IMAGE_authors}"

# Container variables
ENV CTR_user=apache \
    CTR_user_id="48" \
    CTR_cmd="httpd -D FOREGROUND"

# Component bash variables
ENV HTTPD_main_conf_path=/etc/httpd/conf \
    HTTPD_main_conf_file=/etc/httpd/conf/httpd.conf \
    HTTPD_main_conf_d_path=/etc/httpd/conf.d \
    HTTPD_modules_conf_d_path=/etc/httpd/conf.modules.d \
    HTTPD_var_run_path=/var/run/httpd \
    HTTPD_public_path=/var/www/html \
    HTTPD_port=${IMAGE_service_port} \
    HTTPD_log_path=/var/log/httpd

COPY conf/usr/bin/* /usr/bin/
COPY conf/container-entrypoint.d/* ${CTR_entrypoint_opt_path}/

RUN container-setup
RUN install-pkgs httpd

RUN httpd-setup

WORKDIR ${HTTPD_public_path}

USER ${CTR_user_id}

STOPSIGNAL SIGWINCH

EXPOSE ${HTTPD_port}

CMD ${CTR_cmd}
