# image
version_image_suffix: php-fpm
image_from_ctr: php80-fpm
image_tag_from_ctr: "{{ php_version }}-fpm"
dockerfile_builder_image_from_repo_name: php

# source dir
template_path: "{{ template_dir }}/moodle_php-fpm"
