- name: get moodle version from remote source
  when:
    - moodle_git_source_version_url is defined
    - moodle_git_repo_version_regex is defined
  set_fact:
    moodle_git_source_version: "{{ lookup('url', moodle_git_source_version_url) | regex_search(moodle_git_repo_version_regex) }}"

- name: set version based on moodle source
  set_fact:
    version_image_major: "{{ moodle_git_source_version.split('.')[0] | default(false) }}"
    version_image_minor: "{{ moodle_git_source_version.split('.')[1] | default(false) }}"
    version_image_patch: "{{ moodle_git_source_version.split('.')[2] | default(false) }}"
    version_image_build: "{{ moodle_git_commit[0:7] | default(false) }}"
