# platform vars
moodle_version: '3.9'

# moodle
moodle_git_branch: "MOODLE_{{ moodle_version | replace('.','') }}_STABLE"
moodle_git_ref: "{{ lookup('url', dockerfile_builder_image_git_chk) }}"
moodle_git_commit: "{{ moodle_git_ref.object.sha }}"

dockerfile_builder_image_git_remote: "git://github.com/moodle/moodle"
dockerfile_builder_image_git_chk:
  "{{ 'https://api.github.com/repos/moodle/moodle/git/refs/heads/' +
  moodle_git_branch }}"
