# registry
registry_name: "{{ m4e_registry_name }}"

# platform vars
moodle_version: '3.9'

# moodle
moodle_git_branch: "MOODLE_{{ moodle_version | replace('.','') }}_STABLE"
moodle_git_ref: "{{ lookup('url', dockerfile_builder_image_git_chk) }}"
moodle_git_commit: "{{ moodle_git_ref.object.sha }}"

dockerfile_builder_image_git_remote: "git://github.com/moodle/moodle"
dockerfile_builder_image_git_chk:
  "{{ 'https://api.github.com/repos/moodle/moodle/git/refs/heads/' +
  moodle_git_branch }}"
moodle_git_source_version_url:
  "{{ 'https://raw.githubusercontent.com/moodle/moodle/' +
  moodle_git_branch + '/version.php' }}"
moodle_git_repo_version_regex: "([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?"
