centos_version: 9
image_from_ctr: "centos{{ centos_version }}-base"
image_tag_from_ctr: "{{ centos_version }}-base"
dockerfile_builder_image_from_repo_name: centos
dockerfile_builder_image_based: "CentOS {{ centos_version }} Stream minimal"
nginx_version_by_module: "{{ true if nginx_version is defined and nginx_version != nginx_versions.120 else false }}"
remi_repo: "{{ true if php_version is defined and php_version != php_versions.80 else false }}"
