# ci
prepare_image_task: centos8

# prepare
centos8_build_kickstart: "{{ ansible_host }}.ks"
centos8_build_rootfs: "{{ ansible_host }}.tar.xz"
rootfs_creator_image: quay.io/krestomatio/rootfs-creator
