- name: build
  hosts: "{{ play_containers | default('all') }}"
  connection: local
  any_errors_fatal: "{{ play_any_errors_fatal }}"
  diff: "{{ play_diff | default(omit) | bool }}"
  vars_files: "vars/ci.yml"
  environment:
    DOCKER_BUILDKIT: 1
  tasks:
    - name: setup pipeline
      include_tasks: tasks/setup.yml

    - name: build images by group
      loop_control:
        loop_var: build_step
      loop: "{{ groups.keys() | map('regex_search','^build_step_.*') | select('string') | sort }}"
      include_tasks: tasks/build-group.yml

    - name: "upload artifacts"
      include_tasks: tasks/artifact/main.yml
      run_once: true
