- name: release
  hosts: "{{ play_containers | default('all') }}"
  connection: local
  any_errors_fatal: "{{ play_any_errors_fatal }}"
  diff: "{{ play_diff | default(omit) }}"
  vars_files: "vars/ci.yml"
  environment:
    DOCKER_BUILDKIT: 1
  tasks:
    - name: setup pipeline
      include_tasks: tasks/setup.yml

    - name: "download artifacts"
      include_tasks: tasks/artifact/main.yml
      run_once: true

    - name: promote image
      include_tasks: tasks/promote.yml

    - name: release
      include_tasks: tasks/git/release.yml
