- name: check state related vars dir exists
  stat:
    path: "{{ state_path }}"
  register: state_vars_dest_check

- name: create state related vars dir
  when:
    - not ansible_check_mode
    - not state_vars_dest_check.stat.exists
  file:
    dest: "{{ state_path }}"
    state: directory
    mode: '0755'
