- include_tasks: dest.yml

- name: load state related vars
  when:
    - state_vars_load | default(true)
    - state_vars_dest_check.stat.exists
  include_vars:
    dir: "{{ state_path }}"
    ignore_unknown_extensions: True
    extensions:
      - yml

- name: assign respective state variables
  when: load_state_yml
  vars:
    load_state_yml: "{{ lookup('vars', state_name + '_image',default=False) }}"
  block:
    - name: set state tag
      when:
        - state_yml_tag is not defined
        - load_state_yml.tag is defined
      set_fact:
        state_yml_tag: "{{ load_state_yml.tag }}"

    - name: set state ID
      when:
        - state_yml_id is not defined
        - load_state_yml.id is defined
      set_fact:
        state_yml_id: "{{ load_state_yml.id }}"

    - name: set state repo digest
      when:
        - state_yml_repo_digest is not defined
        - load_state_yml.repo_digest is defined
      set_fact:
        state_yml_repo_digest: "{{ load_state_yml.repo_digest }}"

    - name: set state artifact tag
      when:
        - state_yml_artifact_tag is not defined
        - load_state_yml.artifact_tag is defined
      set_fact:
        state_yml_artifact_tag: "{{ load_state_yml.artifact_tag }}"

- name: set fact when artifact matches pipeline's
  when:
    - artifact_tag | default(false)
    - artifact_tag == state_yml_artifact_tag
  set_fact:
    state_image_match_artifact_tag: true
