- include_tasks: dest.yml

- name: load state related vars
  when:
    - state_vars_load | default(true)
    - state_vars_dest_check.stat.exists
  include_vars:
    dir: "{{ state_path }}"
    ignore_unknown_extensions: True
    extensions:
      - yml

- name: set fact when artifact matches pipeline's
  vars:
    pipeline_artifact_tag: "{{ lookup('vars', state_name + '_image').artifact_tag | default(false) }}"
  when:
    - lookup('vars', state_name + '_image', default=False)
    - artifact_tag | default(false)
    - artifact_tag == pipeline_artifact_tag
  set_fact:
    state_image_match_artifact_tag: true
