# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_authors="{{ dockerfile_builder_image_authors }}" \
    IMAGE_version="{{ dockerfile_builder_image_version }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    PHP_version="{{ php_version }}" \
    PHP_ver_short="{{ php_version | replace('.','') }}"

# General variables
ENV IMAGE_name=php-fpm \
    IMAGE_summary="PHP ${PHP_version}" \
    IMAGE_description="This UBI minimal based container image runs \
    PHP ${PHP_version}" \
    IMAGE_title="PHP ${PHP_version}" \
    PHP_FPM_port="9000"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="${IMAGE_authors}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.version="${IMAGE_version}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.expose-services="${PHP_FPM_port}:php-fpm" \
      io.openshift.tags="${IMAGE_name},php,php${PHP_ver_short},php-${PHP_ver_short}" \
      maintainer="${IMAGE_authors}"

# Container variables
ENV CTR_user=apache \
    CTR_user_id="48" \
    CTR_cmd="php-fpm"

# Component bash variables
ENV PHP_run=/run/php-fpm \
    PHP_conf_dir=/etc/php.d \
    PHP_conf_file=/etc/php.ini \
    PHP_sysconf_path=/etc \
    PHP_module_dir=/usr/lib64/php/modules/ \
    PHP_FPM_conf_dir=/etc/php-fpm.d \
    PHP_FPM_conf_file=/etc/php-fpm.conf \
    PHP_FPM_pool_file=/etc/php-fpm.d/www.conf \
    HTTPD_public_path=/var/www/html

ENV OS_install_pkgs="php-fpm php-cli php-opcache"

COPY conf/usr/bin/* /usr/bin/
COPY conf/container-entrypoint.d/* ${CTR_entrypoint_opt_path}/

RUN container-setup
RUN install-pkgs ${OS_install_pkgs}

# Component config variables
ENV PHP_FPM_listen=${PHP_FPM_port} \
    PHP_FPM_user=${CTR_user} \
    PHP_FPM_group=${CTR_group} \
    PHP_FPM_listen_owner=${CTR_user} \
    PHP_FPM_listen_group=${CTR_group} \
    PHP_FPM_listen_allowed_clients="127.0.0.1"

RUN php-fpm-setup

WORKDIR ${HTTPD_public_path}

USER ${CTR_user_id}

STOPSIGNAL SIGQUIT

EXPOSE ${PHP_FPM_port}

CMD ${CTR_cmd}
