centos_version: 9

# rootfs
rootfs_repo_releasever: "{{ centos_version }}"
rootfs_image_base: quay.io/fedora/fedora-minimal:34
rootfs_repo_baseos_gpgkey: 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official'
