# containers generated build dir
template_path: "{{ template_dir }}/nfs-ganesha"

# containers generated build dir
generated_subdir: nfs

# ci
version_release_no_bump: true

# version tags
version_image_major: "{{ nfs_ganesha_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ nfs_ganesha_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ nfs_ganesha_version.split('.')[2] | default(false) }}"
