# image
dockerfile_builder_image_from: "{{ registry_path }}/nginx_php-fpm{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_version: "0.0.1"

# source dir
template_path: "{{ template_dir }}/moodle_nginx"
