#!/bin/bash -e
# description: additional entrypoint script for php-fpm

# listen.allowed_clients with values 'empty' or 'any' does not  work
# so it is remove in that case
if [ ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} != '127.0.0.1' ]; then
    if [[ -z ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} || ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} == 'any' ]]; then
        sed -i "s@^listen.allowed_clients@; listen.allowed_clients@" ${PHP_FPM_POOL_FILE}
    else
        sed -i 's@^listen.allowed_clients.*@listen.allowed_clients = ${PHP_FPM_LISTEN_ALLOWED_CLIENTS}@' ${PHP_FPM_POOL_FILE}
    fi
fi
