dockerfile_builder_image_based: "CentOS 9 Stream minimal"

# containers generated build dir
moodle_version: "{{ moodle_versions.41 }}"
nginx_version: "{{ nginx_versions.120 }}"
php_version: "{{ php_versions.80 }}"
httpd_version: "{{ httpd_versions.24 }}"

# moodle
moodle_git_branch: "MOODLE_401_STABLE"
moodle_install_extra_pkgs: php-sodium php-pecl-redis5 php-pecl-apcu poppler-utils graphviz aspell
