#!/bin/bash -e
# description: additional entrypoint script for php-fpm

# Exit if nginx is installed and php-fpm conf file not writable
if rpm -q nginx &>/dev/null; then
    if ! [ -w "${PHP_FPM_CONF_FILE}" ]; then
        echo "Nginx installed and ${PHP_FPM_CONF_FILE} not writable...doing nothing here"
        exit 0
    fi
fi

# listen.allowed_clients with values 'empty' or 'any' does not  work
# so it is remove in that case
if [ ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} != '127.0.0.1' ]; then
    if [[ -z ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} || ${PHP_FPM_LISTEN_ALLOWED_CLIENTS} == 'any' ]]; then
        sed -i "s@^listen.allowed_clients@; listen.allowed_clients@" ${PHP_FPM_POOL_FILE}
    else
        sed -i 's@^listen.allowed_clients.*@listen.allowed_clients = ${PHP_FPM_LISTEN_ALLOWED_CLIENTS}@' ${PHP_FPM_POOL_FILE}
    fi
fi

# php-fpm default config
# temp copy since no permissions in /etc
cp -pf ${PHP_FPM_CONF_FILE} /tmp/php-fpm.conf
sed -i \
    -e "s@^error_log.*@error_log = ${PHP_FPM_ERROR_LOG}@" \
    -e "s@^daemonize.*@daemonize = no@" \
    -e "s@;\{0,1\}process_control_timeout.*@process_control_timeout = ${PHP_FPM_PROCESS_CONTROL_TIMEOUT}@" \
    /tmp/php-fpm.conf
cp -pf /tmp/php-fpm.conf ${PHP_FPM_CONF_FILE}
rm /tmp/php-fpm.conf

sed -i \
    -e "s@^user =.*@user = ${PHP_FPM_USER}@" \
    -e "s@^group =.*@group = ${PHP_FPM_GROUP}@" \
    -e "s@^slowlog =.*@slowlog = ${PHP_FPM_ACCESS_LOG}@" \
    -e "s@^;\{0,1\}access.log =.*@access.log = ${PHP_FPM_SLOWLOG}@" \
    -e "s@^;\{0,1\}catch_workers_output.*@catch_workers_output = yes@" \
    -e "s@^listen =.*@listen = ${PHP_FPM_LISTEN}@" \
    -e "s@^listen.owner =.*@listen.owner = ${PHP_FPM_LISTEN_OWNER}@" \
    -e "s@^listen.group =.*@listen.group = ${PHP_FPM_LISTEN_GROUP}@" \
    -e "s@^;\{0,1\}php_admin_value\[error_log\].*@;php_admin_value\[error_log\] = ${PHP_FPM_ERROR_LOG}@" \
    ${PHP_FPM_POOL_FILE}

if (("${PHP_VER_SHORT}" >= "80")) && [ "${PHP_FPM_STATUS_LISTEN}" != "${PHP_FPM_LISTEN}" ]; then
    if grep -qE '^;?pm.status_listen' ${PHP_FPM_POOL_FILE}; then
        sed -i \
            -e "s@^;\{0,1\}pm.status_listen =.*@pm.status_listen = ${PHP_FPM_STATUS_LISTEN}@" \
            ${PHP_FPM_POOL_FILE}
    else
        echo "pm.status_listen = ${PHP_FPM_STATUS_LISTEN}" >> ${PHP_FPM_POOL_FILE}
    fi
fi
