- name: check valid builder
  when: assertion_dockerfile_builder | default(false)
  assert:
    that: dockerfile_builder in ['docker','podman']

- name: check artifact tag is defined
  when: assertion_artifact_tag | default(false)
  assert:
    that: artifact_tag is defined and artifact_tag

- name: check release version tag does not exist in git repo
  when:
    - release_version is defined
    - assertion_release_version_tag | default(false)
  command: "git tag -l {{ release_version }}"
  register: release_version_tag_status
  failed_when: release_version_tag_status.stdout is defined and release_version_tag_status.stdout
  changed_when: false

- name: check release version
  when: assertion_release_version | default(false)
  assert:
    that: assertion_release_version is defined and assertion_release_version
