#!/bin/bash -e
# description: additional entrypoint script for moodle nginx

# Exit if php-fpm is installed and nginx conf file not writable
if rpm -q php-fpm &>/dev/null; then
    if ! [ -w "${NGINX_MAIN_CONF_FILE}" ]; then
        echo "PHP-FPM installed and ${NGINX_MAIN_CONF_FILE} not writable...doing nothing here"
        exit 0
    fi
fi

# root default config
if ! [ -f ${NGINX_DEFAULT_CONF_ROOT_FILE} ]; then
    cat << "EOF" > ${NGINX_DEFAULT_CONF_ROOT_FILE}
location / {
    index index.php index.html index.htm;
    try_files $uri $uri/ /index.php;
}
EOF
fi

# php-fpm default config
if ! [ -f ${NGINX_DEFAULT_CONF_APP_FILE} ]; then
    cat << "EOF" > ${NGINX_DEFAULT_CONF_APP_FILE}
location ~ [^/]\.php(/|$) {
    include                         fastcgi_params;
    fastcgi_split_path_info         ^(.+?\.php)(/.*)$;
    fastcgi_index                   index.php;
    fastcgi_pass                    __fastcgi_pass__;
    fastcgi_param   PATH_INFO       $fastcgi_path_info;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
EOF
    sed -i "s@__fastcgi_pass__@${NGINX_FASTCGI_PASS}@" $NGINX_DEFAULT_CONF_APP_FILE
fi
