graphql_engine_version: "{{ graphql_engine_versions.2 }}"
postgres_version: 13
tag_alternative_image_name: "{{ container_image }}"
dockerfile_builder_tags:
  - "{{ graphql_engine_version }}"

# source dir
template_path: "{{ template_dir }}/graphql-engine"

# containers generated build dir
generated_subdir: graphql-engine

# ci
version_release_no_bump: true

# version tags
version_image_major: "{{ graphql_engine_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ graphql_engine_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ graphql_engine_version.split('.')[2] | default(false) }}"

# builder
image_from_ctr: "graphql-engine{{ graphql_engine_version.split('.')[0] | default('') }}-base"
image_tag_from_ctr: 9-base
dockerfile_builder_image_from_repo_name: centos
dockerfile_builder_image_ocp_tags:
  "graphql-engine,graphql-engine-{{ graphql_engine_version.split('.')[0] }},graphql-engine-{{ graphql_engine_version }}"
