# options
dockerfile_builder_pull: true

# image
# dockerfile_builder_image_from: "registry.access.redhat.com/ubi8/ubi-minimal"
# dockerfile_builder_image_based: UBI 8 minimal
# dockerfile_builder_image_ocp_tags: ubi,ubi8

dockerfile_builder_image_from: "{{ registry_path }}/centos8-minimal{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_based: CentOS 8 minimal
dockerfile_builder_image_ocp_tags: centos,centos8
