# platform vars
moodle_version: '3.9'

# moodle
moodle_git_branch: "MOODLE_{{ moodle_version | replace('.','') }}_STABLE"

dockerfile_builder_image_git_remote: "git://github.com/moodle/moodle"
dockerfile_builder_image_git_chk:
  "{{ 'https://api.github.com/repos/moodle/moodle/git/refs/heads/' +
  moodle_git_branch }}"
moodle_git_source_version_url:
  "{{ 'https://raw.githubusercontent.com/moodle/moodle/' +
  moodle_git_branch + '/version.php' }}"
moodle_git_repo_version_regex: "([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?"

# other
version_bump_only_patch: true
