# {{ ansible_managed  }}
ARG ARG_IMAGE_FROM={{ dockerfile_builder_image_from }}
{% if postgres_prev_version_old_pg_bin_image_from is defined and postgres_prev_version_old_pg_bin_image_from %}
FROM {{ postgres_prev_version_old_pg_bin_image_from }} AS old_pg_bin
{% else %}
FROM ${ARG_IMAGE_FROM} AS old_pg_bin
{% endif %}

# Component bash variables
ENV POSTGRES_PREV_VERSION="{{ postgres_prev_version }}"

{% if postgres_prev_version_by_module | default(true) %}
RUN microdnf module enable -y postgresql:${POSTGRES_PREV_VERSION} && \
    install-pkgs postgresql-server && \
{% else %}
RUN install-pkgs postgresql-server && \
{% endif %}
    mkdir -p /opt/pg_bin && \
    cp -rp /usr/bin/{postgres,pg_*} /opt/pg_bin/


FROM ${ARG_IMAGE_FROM}

# General variables
ENV IMAGE_NAME={{ dockerfile_builder_image_name }} \
    IMAGE_SUMMARY="Postgres {{ postgres_version }}" \
    IMAGE_DESCRIPTION="This {{ dockerfile_builder_image_based }} based container image runs Postgres {{ postgres_version }}. \
It follows https://github.com/sclorg/postgresql-container" \
    IMAGE_TITLE="Postgres {{ postgres_version }}" \
    IMAGE_SERVICE_PORT="5432" \
    IMAGE_SERVICE_NAME="postgres" \
    TZ="{{ dockerfile_builder_image_timezone }}"

# Container variables
ENV CTR_USER=postgres \
    CTR_USER_ID="26" \
    CTR_HOME=/var/lib/pgsql \
    CTR_CMD="run-postgresql" \
    CTR_SCRIPTS_PATH=/usr/share/container-scripts/postgresql \
    CTR_STOPSIGNAL=SIGINT

# Component bash variables
ENV POSTGRES_VERSION="{{ postgres_version }}" \
    POSTGRES_PREV_VERSION="{{ postgres_prev_version }}" \
    POSTGRES_PORT=${IMAGE_SERVICE_PORT} \
    POSTGRES_RUN=/var/run/postgresql \
    POSTGRES_HOME=${CTR_HOME} \
    POSTGRES_DATA="${CTR_HOME}/data"

# Frequent environment variables
ENV HOME="${CTR_HOME}" \
    PGUSER="$CTR_USER" \
    LANG="{{ dockerfile_builder_image_lang }}"

ENV OS_INSTALL_PKGS="postgresql-server postgresql-contrib gettext nss_wrapper bind-utils procps-ng psmisc"

USER 0

COPY conf/usr /usr/
COPY conf/container-entrypoint.d ${CTR_ENTRYPOINT_OPT_PATH}/

COPY --from=old_pg_bin /opt/pg_bin/ /usr/lib64/pgsql/postgresql-${POSTGRES_PREV_VERSION}/bin

RUN container-setup && container-setup-postgres

WORKDIR ${CTR_HOME}

USER ${CTR_USER_ID}

STOPSIGNAL ${CTR_STOPSIGNAL}

EXPOSE ${POSTGRES_PORT}

CMD ${CTR_CMD}

# Labels
LABEL name="${IMAGE_NAME}" \
      summary="${IMAGE_SUMMARY}" \
      description="${IMAGE_DESCRIPTION}" \
      maintainer="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.title="${IMAGE_TITLE}" \
      org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.description="${IMAGE_DESCRIPTION}" \
      org.opencontainers.image.version="{{ dockerfile_builder_image_version }}" \
      io.k8s.description="${IMAGE_DESCRIPTION}" \
      io.k8s.display-name="${IMAGE_TITLE}" \
      io.openshift.expose-services="${IMAGE_SERVICE_PORT}:${IMAGE_SERVICE_NAME}" \
      io.openshift.tags="${IMAGE_NAME},postgres,postgres-${POSTGRES_VERSION},postgres${POSTGRES_VERSION}"
