# image
dockerfile_builder_image_from: "{{ registry_path }}/base{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_version:
  "{{ postgres_version + '.' +   (git_commit|default('0')) }}"
dockerfile_builder_image_lang: es_CR.UTF-8
