dockerfile_builder_arg_image_from_registry_path: "{{ build_registry_path }}"
version_include_fallback_tags: true
pr_commit_tag:
  "{{ lookup('env','PULL_PULL_SHA') | default(git_head_commit,true) |
  default(lookup('pipe', 'git rev-parse HEAD 2> /dev/null  || echo')) |
  default(false) }}"
version_commit_tag: "{{ pr_commit_tag }}"
version_commit_tag_short: "{{ version_commit_tag[:7] }}"
version_image_prerelease: "{{ lookup('env','PRERELEASE') |
  default(ctr_name_hash_short + '-' + version_commit_tag_short,true) | default(false) }}"
artifact_tag: "{{ pr_commit_tag }}"
state_yml_artifact_tag: "{{ artifact_tag }}"
state_yml_relative_path: "{{ generated_relative_path }}"
state_yml_tags: "{{ version_image_derivative_tags | default([]) | join(',') | default('') }}"
state_yml_name: "{{ ctr_variant_name }}"
assertion_artifact_tag: true
artifact_generated_context_task: upload
artifact_generated_context_path: "{{ generated_dir }}/*/"
artifact_state_task: upload
build_pipeline: true
