# image
postgres_version: "{{ postgres_versions.16 }}"
postgres_prev_version: "{{ postgres_prev_versions.16 }}"
postgres_prev_version_old_pg_bin_image_from: quay.io/krestomatio/rocky:9-base
postgres_prev_version_by_module: false
dockerfile_builder_image_lang: en_US.UTF-8
