# image
postgres_version: "{{ postgres_versions.16 }}"
postgres_prev_version: "{{ postgres_prev_versions[postgres_version | int] }}"
postgres_prev_version_by_module: false
postgres_version_by_module: "{{ true if postgres_version is defined and (image_tag_from_ctr == '9-base' and postgres_version >= postgres_versions.16) else false }}"
dockerfile_builder_image_lang: en_US.UTF-8
