# image
# dockerfile_builder_image_from: "registry.access.redhat.com/ubi8/ubi-minimal"
# dockerfile_builder_image_based: UBI 8 minimal

container_builder_image_from: rocky8-minimal
dockerfile_builder_image_based: Rocky Linux 8 minimal
dockerfile_builder_image_ocp_tags: rocky,rocky8
