#!/bin/bash -ue
# description: check keydb container

usage() {
    cat 1>&2 <<EOF
Script to check keydb container.

ENVIRONMENT VARS:
KEYDB_PORT              tcp port keydb listen to
KEYDB_PASSWORD          keydb require password

USAGE:
    check-container-keydb [OPTIONS]

OPTIONS (check moodle php container):
  -l            check liveness
  -r            check readiness

EXAMPLES:
    check-container -l
    check-container -r
EOF
}

handle_auth(){
    if [ -z ${KEYDB_PASSWORD+x} ]; then
        echo "KEYDB_PASSWORD is not set"
    else
        export REDISCLI_AUTH="${KEYDB_PASSWORD}"
    fi
}

check_ping() {
    handle_auth
    keydb-cli -h 127.0.0.1 -p ${KEYDB_PORT} ping
}

check_readiness() {
    check_ping
}

check_liveness() {
    check_ping
}

while getopts ":lr" opt; do
  case ${opt} in
    l )
        check_readiness
        ;;
    r )
        check_liveness
        ;;
    \? )
        usage
        exit
        ;;
  esac
done
shift $((OPTIND -1))

if (( $OPTIND == 1 )); then
    echo -e "No check. Use an option:\n"
    usage
    exit
fi
