- name: git config
  when: "(git_config_list | default(false) | type_debug) == 'list'"
  with_items: "{{ git_config_list }}"
  git_config:
    name: "{{ item.name | default(omit) }}"
    scope: "{{ item.scope | default('local') }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    repo: "{{ item.repo | default(git_repo_dir) | default(playbook_dir) }}"
    list_all: "{{ item.list_all | default(omit) }}"

- name: fetch git tags
  when: git_config_fetch_tag | default(true)
  changed_when: false
  command: git fetch --tags

- name: set version based on git tags
  when: git_version_dict is not defined
  vars:
    git_version_bump: patch
  set_fact:
    git_version_dict: "{{ lookup('git_semver', git_repo_dir | default(playbook_dir),
      bump=git_version_bump, want='dict') }}"

- name: check version tag does not exist
  when:
    - git_version_dict is defined
    - check_git_version_tag | default(false)
  command: "git tag -l {{ git_version_dict.full }}"
  register: git_version_tag_status
  failed_when: git_version_tag_status.stdout is defined and git_version_tag_status.stdout
  changed_when: false

- name: show git version
  debug:
    msg: "{{ git_version_dict }}"

- name: get git HEAD's commit
  when: git_head_commit is not defined
  set_fact:
    git_head_commit: "{{ lookup('pipe', 'git rev-parse HEAD') | default(false) }}"

- name: show git HEAD's commit
  debug:
    msg: "{{ git_head_commit }}"

- name: update git submodules
  when: git_config_submodule_update | default(true) | bool
  changed_when: git_config_submodule_update_status.stdout is defined and git_config_submodule_update_status.stdout
  register: git_config_submodule_update_status
  command: git submodule update --init --recursive
