ctr_repo_name: nginx
ctr_version: "{{ nginx_version }}"

# version tags
version_image_major: "{{ nginx_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ nginx_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ nginx_version.split('.')[2] | default(false) }}"
