# containers generated build dir
template_path: "{{ template_dir }}/nginx"

# containers generated build dir
generated_subdir: nginx

# version tags
version_image_major: "{{ nginx_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ nginx_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ nginx_version.split('.')[2] | default(false) }}"
