# image
image_from_ctr: moodle40_nginx120_php80-fpm
image_tag_from_ctr: "{{ moodle_version }}-nginx_php-fpm"
dockerfile_builder_image_from_repo_name: moodle
dockerfile_builder_image_summary: "PHP $PHP_VERSION and NGINX ${NGINX_VERSION} for Moodle {{ moodle_version }}"
dockerfile_builder_image_description: "This {{ dockerfile_builder_image_based }} based container image runs PHP ${PHP_VERSION} or NGINX ${NGINX_VERSION} for Moodle {{ moodle_version }}"
dockerfile_builder_image_title: "PHP ${PHP_VERSION} and NGINX ${NGINX_VERSION} for Moodle {{ moodle_version }}"
dockerfile_builder_image_ocp_tags:
  "{{ '${IMAGE_NAME},php,php-fpm,php${PHP_VER_SHORT},php-${PHP_VER_SHORT}'
  + ',nginx,nginx-${NGINX_VER_SHORT},nginx${NGINX_VER_SHORT}'
  + ',moodle,moodle${MOODLE_VER_SHORT},moodle-${MOODLE_VER_SHORT}' }}"
dockerfile_builder_args:
  ARG_GIT_COMMIT: "{{ moodle_git_commit }}"

# source dir
template_path: "{{ template_dir }}/moodle_php-fpm"
