# origin
origin_name: gitlab.com

# registry
registry_name: quay.io
registry_project: krestomatio

# builder
# dockerfile_builder_push: true
dockerfile_builder_image_timezone: UTC
dockerfile_builder_image_authors: Job Céspedes Ortiz <jobcespedes@gmail.com>
