# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

ENV IMAGE_VERSION="{{ dockerfile_builder_image_version }}" \
    IMAGE_CREATED="{{ dockerfile_builder_image_created }}" \
    MOODLE_VERSION="{{ moodle_version }}" \
    MOODLE_VER_SHORT="{{ moodle_version | replace('.','') }}" \
    TZ="{{ dockerfile_builder_image_timezone }}"

ENV NAME="moodle_httpd" \
    SUMMARY="Apache2 ${APACHE_VERSION} for Moodle" \
    DESCRIPTION="This UBI minimal based container image runs \
    Apache ${APACHE_VERSION} for Moodle" \
    TITLE="Apache ${APACHE_VERSION} for Moodle"

LABEL org.opencontainers.image.title="${TITLE}" \
      org.opencontainers.image.description="${DESCRIPTION}" \
      org.opencontainers.image.version="${IMAGE_VERSION}" \
      org.opencontainers.image.created="${IMAGE_CREATED}" \
      name="${NAME}" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.description="${DESCRIPTION}" \
      io.k8s.display-name="${TITLE}" \
      io.openshift.tags="${NAME},apache,apache${APACHE_VER_SHORT},apache-${APACHE_VER_SHORT},moodle,moodle${MOODLE_VER_SHORT},moodle-${MOODLE_VER_SHORT}"

USER 0
RUN container-setup
USER $CUSER
