# image
container_builder_image_from: moodle_nginx_web
dockerfile_builder_image_name: "{{ ctr_name }}"
dockerfile_builder_image_summary: "PHP $PHP_VERSION and NGINX ${NGINX_VERSION} for Moodle {{ moodle_version }}"
dockerfile_builder_image_description: "This {{ dockerfile_builder_image_based }} based container image runs PHP ${PHP_VERSION} or NGINX ${NGINX_VERSION} for Moodle {{ moodle_version }}"
dockerfile_builder_image_title: "PHP ${PHP_VERSION} and NGINX ${NGINX_VERSION} for Moodle {{ moodle_version }}"
dockerfile_builder_image_ocp_tags:
  "{{ '${IMAGE_NAME},php,php-fpm,php${PHP_VER_SHORT},php-${PHP_VER_SHORT}'
  + ',nginx,nginx-${NGINX_VER_SHORT},nginx${NGINX_VER_SHORT}'
  + ',moodle,moodle${MOODLE_VER_SHORT},moodle-${MOODLE_VER_SHORT}' }}"
dockerfile_builder_force:
  "{{ true if hostvars['moodle_app'].dockerfile_builder_image_build is defined
  and hostvars['moodle_app'].dockerfile_builder_image_build is changed else false  }}"
dockerfile_builder_force_source: "{{ dockerfile_builder_force }}"

# source dir
template_path: "{{ template_dir }}/moodle_php-fpm"

# ci
prepare_image_task: moodle
version_release_no_bump: true

# other
moodle_php_redis_build: true
moodle_app_copy_from: "{{ registry_path }}/moodle_app{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
