ctr_repo_name: postgres
ctr_version: "{{ postgres_version }}"

# version tags
version_image_major: "{{ postgres_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ postgres_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ postgres_version.split('.')[2] | default(false) }}"
