# image
version_image_suffix: bundle
image_from_ctr: moodle41
image_tag_from_ctr: "{{ moodle_version }}"
dockerfile_builder_image_from_repo_name: moodle

# source dir
template_path: "{{ template_dir }}/moodle_bundle"

# ci
prepare_image_task: moodle
version_release_no_bump: true

# moodle
moodle_plugin_list: mod_attendance mod_checklist mod_customcert block_checklist gradeexport_checklist
