# image
version_image_suffix: bundle
image_from_ctr: moodle41
image_tag_from_ctr: "{{ moodle_version }}"
dockerfile_builder_image_from_repo_name: moodle

# source dir
template_path: "{{ template_dir }}/moodle_bundle"

# moodle
moodle_plugin_list:
  - mod_attendance
  - mod_checklist
  # - mod_customcert # once it becomes avaiable for 4.1
  - block_checklist
  - gradeexport_checklist
