
# platform vars
image_ansible_version: '2.9'
molecule_version: '3.0'
buildah_version: 'stable'

# options
dockerfile_builder_pull: true

dockerfile_builder_image_from: "quay.io/buildah/{{ buildah_version }}"
dockerfile_builder_image_based: "Buildah Stable Image"
dockerfile_builder_image_ocp_tags: "ansible,ansible{{ image_ansible_version }},buildah,buildah-{{ buildah_version }}"
