working_dir: "{{ playbook_dir }}"

# container
ctr_name: "{{ inventory_hostname }}"

## state name must comply with ansible variable name convention
state_name: "{{ ctr_name | replace('-', '_') | lower }}"
state_dir: "{{ working_dir }}/vars/state"
state_file: "{{ state_dir }}/{{ ctr_name }}.yml"

git_repo_dir: "{{  working_dir }}/../"
version_image_dir: "{{ git_repo_dir }}"

# containers template dir
template_dir: "{{ working_dir }}/templated_contexts"
template_path: "{{template_dir }}/{{ ctr_name }}"

# containers generated build dir
generated_dir: "{{ git_repo_dir }}"
generated_path: "{{ generated_dir }}/{{ ctr_name }}"

# registry
registry_name: "quay.io"
registry_project: krestomatio
registry_path: "{{ registry_name + '/' if registry_name else '' }}{{registry_project}}"
cache_registry_name: gcr.io
build_registry_name: gcr.io

# container image
container_image: "{{ registry_path }}/{{ ctr_name }}"

# build vars
dockerfile_builder: docker
# dockerfile_builder_push: true
dockerfile_builder_image_timezone: UTC
dockerfile_builder_image_authors: Job Céspedes Ortiz <jobcespedes@gmail.com>
dockerfile_builder_image_based: CentOS 8 minimal
dockerfile_builder_image_from:
  "{{ registry_path }}/{{ container_builder_image_from }}{{ ':' + container_builder_image_tag_from
  if container_builder_image_tag_from is defined
  and container_builder_image_tag_from else '' }}"
dockerfile_builder_image: "{{ container_image }}"
dockerfile_builder_path: "{{ generated_path }}"
dockerfile_builder_src: "{{ template_path }}"
dockerfile_builder_sync_checksum: true

# doc
doc_generate_project_readme: true
doc_project_readme_src: README.md.j2
doc_project_readme_dest: "{{ git_repo_dir }}/README.md"
