# platform vars
php_versions:
  80: '8.0'
httpd_versions:
  24: '2.4'
nginx_versions:
  120: '1.20'
postgres_versions:
  13: '13'
postgres_prev_versions:
  13: '10'
keydb_versions_pkg:
  63: '6.3.1-1'
keydb_versions:
  63: "{{ keydb_versions_pkg.63 | regex_search(external_release_version_regex) }}"
nfs_ganesha_versions:
  40: '4.0.7'
node_versions:
  14: '14'
node_version_name:
  14: fermium
  16: gallium
moodle_versions:
  41: '4.1'
graphql_engine_versions:
  2: '2.12.0'
go_versions:
  118: '1.18'

working_dir: "{{ playbook_dir }}"

# container
ctr_name: "{{ inventory_hostname }}"
ctr_repo_name: "{{ ctr_name }}"
ctr_variant_name: >-
  {%- if ctr_repo_name == ctr_name -%}
  {{ ctr_repo_name }}
  {%- else -%}
  {{ ctr_repo_name }}:{{ ctr_version }}{{ '-' + version_image_suffix if
  version_image_suffix is defined and version_image_suffix else '' }}
  {%- endif -%}
ctr_name_hash: "{{ ctr_name | hash('md5') }}"
ctr_name_hash_short: "{{ ctr_name_hash[:7] }}"

## state name must comply with ansible variable name convention
state_name: "{{ ctr_name | replace('-', '_') | lower }}"
state_dir: "{{ working_dir }}/vars/state"
state_file: "{{ state_dir }}/{{ ctr_name }}.yml"

git_repo_dir: "{{  working_dir }}/../"
version_image_dir: "{{ git_repo_dir }}"
version_ctr_name: "{{ ctr_name }}"
version_ctr_repo_name: "{{ ctr_repo_name }}"

# containers template dir
template_dir: "{{ working_dir }}/files/templated_contexts"
template_path: "{{template_dir }}/{{ ctr_repo_name }}"

# containers generated build dir
generated_dir: "{{  working_dir }}/.."
generated_subdir: "{{ ctr_repo_name if ctr_repo_name != ctr_name else '' }}"
generated_path: "{{ generated_dir }}{{ '/' + generated_subdir + '/' if
  generated_subdir != '' else '' }}/{{ ctr_name }}"
generated_relative_path: "{{ generated_path | relpath(working_dir + '/..') }}"

# registry
registry_name: "quay.io"
registry_project: krestomatio
registry_path: "{{ registry_name + '/' if registry_name else '' }}{{ registry_project }}"
cache_registry_name: "{{ registry_name }}"
build_registry_name: "{{ registry_name }}"
build_registry_project: "{{ registry_project }}"
build_registry_path: "{{ build_registry_name + '/' if build_registry_name else '' }}{{ build_registry_project }}"

# container image
container_image: "{{ registry_path }}/{{ ctr_repo_name }}"
container_image_variant: >-
  {%- if ctr_repo_name == ctr_name -%}
  {{ container_image }}
  {%- else -%}
  {{ container_image }}:{{ ctr_version }}{{ '-' + version_image_suffix if
  version_image_suffix is defined and version_image_suffix else '' }}
  {%- endif -%}
build_container_image: "{{ build_registry_path }}/{{ ctr_repo_name }}"

# regex
external_release_version_regex: ^([0-9]+)\.([0-9]+)\.([0-9]+)

# build vars
dockerfile_builder: docker
dockerfile_builder_use_buildx: true
dockerfile_builder_buildx_multiplatform_cache: false
dockerfile_builder_buildx_cache_image_extra_tag: "{{ ctr_name }}"
dockerfile_builder_platforms:
  - 'linux/amd64'
  - 'linux/arm64'
dockerfile_builder_push: "{{ true if dockerfile_builder_use_buildx else false }}"
dockerfile_builder_image_timezone: UTC
dockerfile_builder_image_authors: Job Céspedes Ortiz <jobcespedes@krestomatio.com>
dockerfile_builder_image_from_registry_path: "quay.io/krestomatio"
dockerfile_builder_image_from_repo_name: "{{ image_from_ctr | default('') }}"
dockerfile_builder_image_from_tag: "{{ image_tag_from_ctr
  if image_tag_from_ctr is defined
  and image_tag_from_ctr else false }}"
dockerfile_builder_image_from: |-
  {%- if dockerfile_builder_image_from_repo_name != '' -%}
  {{ dockerfile_builder_image_from_registry_path }}/{{ dockerfile_builder_image_from_repo_name }}{{ ':' + dockerfile_builder_image_from_tag if dockerfile_builder_image_from_tag | default(false,true) else '' }}
  {%- else -%}
  {{ false }}
  {%- endif -%}
dockerfile_builder_arg_image_from_registry_path: "{{ dockerfile_builder_image_from_registry_path }}"
dockerfile_builder_arg_image_from_repo_name: "{{ dockerfile_builder_image_from_repo_name }}"
dockerfile_builder_arg_image_from_tag:
  "{{ image_from_ctr if image_from_ctr | default('',true) !=
  dockerfile_builder_arg_image_from_repo_name | default('',true)
  else dockerfile_builder_image_from_tag }}"
dockerfile_builder_arg_image_from: |-
  {%- if dockerfile_builder_arg_image_from_repo_name | default(false) -%}
  {{ dockerfile_builder_arg_image_from_registry_path + '/' + dockerfile_builder_arg_image_from_repo_name }}{{ ':' + dockerfile_builder_arg_image_from_tag if dockerfile_builder_arg_image_from_tag | default(false,true) else '' }}
  {%- else -%}
  {{ false }}
  {%- endif -%}
dockerfile_builder_image: "{{ build_container_image if build_pipeline | default(false)
  else container_image }}{{ ':' + ctr_name if ctr_repo_name != ctr_name else '' }}"
dockerfile_builder_image_name: "{{ ctr_variant_name }}"
dockerfile_builder_path: "{{ generated_path }}"
dockerfile_builder_src: "{{ template_path }}"
dockerfile_builder_sync_checksum: true
dockerfile_builder_pull: "{{ true if dockerfile_builder_use_buildx else false }}"
dockerfile_builder_throttle: 4

# skopeo
skopeo_src_image: "{{ lookup('vars', state_name + '_image').repo_digest }}"
skopeo_dest_image: "{{ container_image_variant }}"
skopeo_dest_image_tags: "{{ dockerfile_builder_tags }}"

# doc
ctr_readme_section_variant_title: "{{ ctr_variant_name }}"
doc_generate_project_readme: true
doc_generate_project_readme_src: README.md.j2
doc_generate_project_readme_dest: "{{ git_repo_dir }}/README.md"
doc_generate_ctr_repo_readme: "{{ true if ctr_repo_name != ctr_name else false }}"
doc_generate_ctr_repo_readme_src: CTR-REPO-README.md.j2
doc_generate_ctr_repo_readme_dest: "{{ generated_path }}/../README.md"

# pushrm
promote_pushrm_bin: docker-pushrm
promote_pushrm_file: "{{ doc_generate_ctr_repo_readme_dest if ctr_repo_name != ctr_name else generated_path + '/README.md' }}"
promote_pushrm_image: "{{ container_image }}"

# updatebot
updatebot_ansible_collection_template_src: updatebot-ansible-collection.yaml.j2
updatebot_ansible_collection_template_dest: "{{ git_repo_dir }}/.lighthouse/updatebot-ansible-collection.yaml"
