# platform vars
php_version: '7.4'
httpd_version: '2.4'
nginx_version: '1.20'
postgres_version: '13'
postgres_prev_version: '10'
keydb_version_pkg: 6.3.1-1
keydb_version: "{{ keydb_version_pkg | regex_search(external_release_version_regex) }}"
nfs_ganesha_version: '4.0.7'
node_version: '14'
moodle_version: '3.9'

node_version_name:
  '14': fermium
  '16': gallium

working_dir: "{{ playbook_dir }}"

# container
ctr_name: "{{ inventory_hostname }}"

## state name must comply with ansible variable name convention
state_name: "{{ ctr_name | replace('-', '_') | lower }}"
state_dir: "{{ working_dir }}/vars/state"
state_file: "{{ state_dir }}/{{ ctr_name }}.yml"

git_repo_dir: "{{  working_dir }}/../"
version_image_dir: "{{ git_repo_dir }}"

# containers template dir
template_dir: "{{ working_dir }}/files/templated_contexts"
template_path: "{{template_dir }}/{{ ctr_name }}"

# containers generated build dir
generated_dir: "{{  working_dir }}/../{{ generated_subdir + '/' if generated_subdir is defined else '' }}"
generated_path: "{{ generated_dir }}/{{ ctr_name }}"
generated_relative_path: "{{ generated_path | relpath(working_dir + '/..') }}"

# registry
registry_name: "quay.io"
registry_project: krestomatio
registry_path: "{{ registry_name + '/' if registry_name else '' }}{{ registry_project }}"
cache_registry_name: "{{ registry_name }}"
build_registry_name: "{{ registry_name }}"
build_registry_project: "{{ registry_project }}"
build_registry_path: "{{ build_registry_name + '/' if build_registry_name else '' }}{{ build_registry_project }}"

# container image
container_image: "{{ registry_path }}/{{ ctr_name }}"
build_container_image: "{{ build_registry_path }}/{{ ctr_name }}"

# regex
external_release_version_regex: ^([0-9]+)\.([0-9]+)\.([0-9]+)

# build vars
dockerfile_builder: docker
dockerfile_builder_use_buildx: true
dockerfile_builder_buildx_multiplatform_cache: false
dockerfile_builder_platforms:
  - 'linux/amd64'
  - 'linux/arm64'
dockerfile_builder_push: "{{ true if dockerfile_builder_use_buildx else false }}"
dockerfile_builder_image_timezone: UTC
dockerfile_builder_image_authors: Job Céspedes Ortiz <jobcespedes@krestomatio.com>
dockerfile_builder_image_based: CentOS 8 Stream minimal
dockerfile_builder_image_from_registry_path: "quay.io/krestomatio"
dockerfile_builder_image_from_name: "{{ container_builder_image_from | default(false) }}"
dockerfile_builder_image_from_tag: "{{ container_builder_image_tag_from
  if container_builder_image_tag_from is defined
  and container_builder_image_tag_from else false }}"
dockerfile_builder_image_from: |-
  {%- if container_builder_image_from is defined and container_builder_image_from -%}
  {{ dockerfile_builder_image_from_registry_path }}/{{ dockerfile_builder_image_from_name }}{{ ':' + dockerfile_builder_image_from_tag if dockerfile_builder_image_from_tag else '' }}
  {%- else -%}
  {{ false }}
  {%- endif -%}
dockerfile_builder_arg_image_from_registry_path: "{{ dockerfile_builder_image_from_registry_path }}"
dockerfile_builder_arg_image_from_name: "{{ dockerfile_builder_image_from_name }}"
dockerfile_builder_arg_image_from_tag: "{{ dockerfile_builder_image_from_tag }}"
dockerfile_builder_arg_image_from: |-
  {%- if container_builder_image_from is defined and container_builder_image_from -%}
  {{ dockerfile_builder_arg_image_from_registry_path + '/' + dockerfile_builder_arg_image_from_name }}{{ ':' + dockerfile_builder_arg_image_from_tag if dockerfile_builder_arg_image_from_tag else '' }}
  {%- else -%}
  {{ false }}
  {%- endif -%}
dockerfile_builder_image: "{{ build_container_image if build_pipeline | default(false)
  else container_image }}"
dockerfile_builder_image_name: "{{ ctr_name }}"
dockerfile_builder_path: "{{ generated_path }}"
dockerfile_builder_src: "{{ template_path }}"
dockerfile_builder_sync_checksum: true
dockerfile_builder_pull: "{{ true if dockerfile_builder_use_buildx else false }}"
dockerfile_builder_throttle: 4

# doc
doc_generate_project_readme: true
doc_project_readme_src: README.md.j2
doc_project_readme_dest: "{{ git_repo_dir }}/README.md"

# updatebot
updatebot_ansible_collection_template_src: updatebot-ansible-collection.yaml.j2
updatebot_ansible_collection_template_dest: "{{ git_repo_dir }}/.lighthouse/updatebot-ansible-collection.yaml"
