ctr_repo_name: php
ctr_version: "{{ php_version }}"
template_path: "{{ template_dir }}/php-fpm"

# version tags
version_image_major: "{{ php_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ php_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ php_version.split('.')[2] | default(false) }}"
