# {{ ansible_managed  }}
ARG ARG_IMAGE_FROM={{ dockerfile_builder_image_from }}
FROM ${ARG_IMAGE_FROM}

# General variables
ENV IMAGE_NAME={{ dockerfile_builder_image_name }} \
    IMAGE_SUMMARY="Nodejs {{ node_version }} image based on {{ dockerfile_builder_image_based }}" \
    IMAGE_DESCRIPTION="{{ dockerfile_builder_image_based }} based image with node {{ node_version }} javascript runtime" \
    IMAGE_TITLE="Node image based on {{ dockerfile_builder_image_based }}"

# Component bash variables
ENV NODE_VERSION="{{ node_version }}"

# Container variables
ENV CTR_CMD="node" \
    CTR_USER=node \
    CTR_USER_ID="1001" \
    CTR_USER_GECOS="Node user" \
    CTR_HOME="/home/node"

# Frequent environment variables
ENV HOME="${CTR_HOME}"

{% if node_version_by_module | default(true) %}
RUN containeruser-create; ${CTR_PKG_MGM} module enable nodejs:{{ node_version }}; install-pkgs nodejs
{% else %}
RUN containeruser-create; install-pkgs nodejs
{% endif %}

USER ${CTR_USER_ID}

WORKDIR ${CTR_HOME}

CMD $CTR_CMD

# Labels
LABEL name="${IMAGE_NAME}" \
    summary="${IMAGE_SUMMARY}" \
    maintainer="{{ dockerfile_builder_image_authors }}" \
    description="${IMAGE_DESCRIPTION}" \
    org.opencontainers.image.title="${IMAGE_TITLE}" \
    org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
    org.opencontainers.image.description="${IMAGE_DESCRIPTION}" \
    io.k8s.description="${IMAGE_DESCRIPTION}" \
    io.k8s.display-name="${IMAGE_TITLE}" \
    io.openshift.tags="${IMAGE_NAME},{{ dockerfile_builder_image_ocp_tags }}"
