- name: set jx2 version
  run_once: true
  retries: 3
  delay: 3
  until: jx2_version_from_url is defined
  vars:
    jx2_version_from_url: "{{ lookup('url', jx2_version_url) | regex_search(jx2_version_regex) }}"
  when:
    - jx2_version_install | default(false)
    - jx2_version_url is defined
    - jx2_version_regex is defined
    - jx2_version is not defined
  set_fact:
    jx2_version: "{{ jx2_version_from_url }}"

- name: set jx3 version
  run_once: true
  retries: 3
  delay: 3
  until: jx3_version_from_url is defined
  vars:
    jx3_version_from_url: "{{ lookup('url', jx3_version_url) | regex_search(jx3_version_regex) }}"
  when:
    - jx3_version_install | default(false)
    - jx3_version_url is defined
    - jx3_version_regex is defined
    - jx3_version is not defined
  set_fact:
    jx3_version: "{{ jx3_version_from_url }}"

- name: set oras version
  run_once: true
  retries: 3
  delay: 3
  until: oras_version_from_url is defined
  vars:
    oras_version_from_url: "{{ lookup('url', oras_version_url) | regex_search(oras_version_regex) }}"
  when:
    - oras_version_install | default(false)
    - oras_version_url is defined
    - oras_version_regex is defined
    - oras_version is not defined
  set_fact:
    oras_version: "{{ oras_version_from_url }}"

- name: set pushrm version
  run_once: true
  retries: 3
  delay: 3
  until: pushrm_version_from_url is defined
  vars:
    pushrm_version_from_url: "{{ lookup('url', pushrm_version_url) | regex_search(pushrm_version_regex) }}"
  when:
    - pushrm_version_install | default(false)
    - pushrm_version_url is defined
    - pushrm_version_regex is defined
    - pushrm_version is not defined
  set_fact:
    pushrm_version: "{{ pushrm_version_from_url }}"

- name: set buildx version
  run_once: true
  retries: 3
  delay: 3
  until: buildx_version_from_url is defined
  vars:
    buildx_version_from_url: "{{ lookup('url', buildx_version_url) | regex_search(buildx_version_regex) }}"
  when:
    - buildx_version_install | default(false)
    - buildx_version_url is defined
    - buildx_version_regex is defined
    - buildx_version is not defined
  set_fact:
    buildx_version: "{{ buildx_version_from_url }}"

- name: set terraform version
  run_once: true
  retries: 3
  delay: 3
  until: terraform_version_from_url is defined
  vars:
    terraform_version_from_url: "{{ lookup('url', terraform_version_url) | regex_search(terraform_version_regex) }}"
  when:
    - terraform_version_install | default(false)
    - terraform_version_url is defined
    - terraform_version_regex is defined
    - terraform_version is not defined
  set_fact:
    terraform_version: "{{ terraform_version_from_url }}"
