# image
dockerfile_builder_image_from: "{{ registry_path }}/nginx{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_version:
  "{{ nginx_version + '.' + (git_commit|default('0')) }}"

# source dir
template_path: "{{ template_dir }}/php-fpm"
