# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General variables
ENV IMAGE_name=httpd \
    IMAGE_summary="Apache {{ httpd_version }}" \
    IMAGE_description="This {{ dockerfile_builder_image_based }} based container image runs Apache {{ httpd_version }}" \
    IMAGE_title="Apache {{ httpd_version }}" \
    IMAGE_service_port="8080" \
    IMAGE_service_name="http"

# Container variables
ENV CTR_user=apache \
    CTR_user_id="48" \
    CTR_cmd="httpd -D FOREGROUND" \
    CTR_stopsignal=SIGWINCH

# Component bash variables
ENV HTTPD_version="{{ httpd_version }}" \
    HTTPD_ver_short="{{ httpd_version | replace('.','') }}" \
    HTTPD_main_conf_path=/etc/httpd/conf \
    HTTPD_main_conf_file=/etc/httpd/conf/httpd.conf \
    HTTPD_main_conf_d_path=/etc/httpd/conf.d \
    HTTPD_modules_conf_d_path=/etc/httpd/conf.modules.d \
    HTTPD_var_run_path=/var/run/httpd \
    HTTPD_port=${IMAGE_service_port} \
    HTTPD_log_path=/var/log/httpd \
    APP_dest=/var/www/html

USER 0

COPY conf/usr/bin/* /usr/bin/
COPY conf/container-entrypoint.d/* ${CTR_entrypoint_opt_path}/

RUN container-setup
RUN install-pkgs httpd

RUN container-setup-httpd

WORKDIR ${APP_dest}

USER ${CTR_user_id}

STOPSIGNAL ${CTR_stopsignal}

EXPOSE ${HTTPD_port}

CMD ${CTR_cmd}

# Labels
LABEL name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      maintainer="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.version="{{ dockerfile_builder_image_version }}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.expose-services="${IMAGE_service_port}:${IMAGE_service_name}" \
      io.openshift.tags="${IMAGE_name},apache,apache-${HTTPD_ver_short},apache${HTTPD_ver_short}"
