# image
dockerfile_builder_image_from: "{{ registry_path }}/php-fpm{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined else '' }}"
dockerfile_builder_image_version: "0.0.1"
