# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

ENV IMAGE_AUTHORS="{{ dockerfile_builder_image_authors }}" \
    IMAGE_VERSION="{{ dockerfile_builder_image_version }}" \
    IMAGE_CREATED="{{ dockerfile_builder_image_created }}" \
    APACHE_VERSION="{{ apache_version }}" \
    APACHE_VER_SHORT="{{ apache_version | replace('.','') }}"

ENV NAME=httpd \
    SUMMARY="Apache2 $APACHE_VERSION" \
    DESCRIPTION="This UBI minimal based container image runs \
    Apache ${APACHE_VERSION}" \
    TITLE="Apache ${APACHE_VERSION}" \
    HTTPD_PORT="8080"

LABEL org.opencontainers.image.title="${TITLE}" \
      org.opencontainers.image.authors="${IMAGE_AUTHORS}" \
      org.opencontainers.image.description="${DESCRIPTION}" \
      org.opencontainers.image.version="${IMAGE_VERSION}" \
      org.opencontainers.image.created="${IMAGE_CREATED}" \
      name="${NAME}" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.description="${DESCRIPTION}" \
      io.k8s.display-name="${TITLE}" \
      io.openshift.expose-services="${HTTPD_PORT}:http" \
      io.openshift.tags="${NAME},apache,apache-${APACHE_VER_SHORT},apache${APACHE_VER_SHORT}" \
      maintainer="${IMAGE_AUTHORS}"

ENV CUSER=apache \
    CUSER_ID="48" \
    CMD="httpd -D FOREGROUND"

ENV HTTPD_MAIN_CONF_PATH=/etc/httpd/conf \
    HTTPD_MAIN_CONF_D_PATH=/etc/httpd/conf.d \
    HTTPD_MODULES_CONF_D_PATH=/etc/httpd/conf.modules.d \
    HTTPD_VAR_RUN=/run/httpd \
    HTTPD_PUBLIC_PATH=/var/www/html \
    HTTPD_DATA_ORIG_PATH=/var/www \
    HTTPD_LOG_PATH=/var/log/httpd \
    HTTPD_VAR_PATH=/var

COPY conf/usr/bin/* /usr/bin/

RUN container-setup
RUN install-pkgs httpd
RUN httpd-setup

WORKDIR ${HTTPD_PUBLIC_PATH}

USER ${CUSER_ID}

STOPSIGNAL SIGWINCH

EXPOSE ${HTTPD_PORT}

ENTRYPOINT ["container-entrypoint"]

CMD $CMD
