# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_authors="{{ dockerfile_builder_image_authors }}" \
    IMAGE_version="{{ dockerfile_builder_image_version }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    APACHE_version="{{ apache_version }}" \
    APACHE_ver_short="{{ apache_version | replace('.','') }}"

# General variables
ENV IMAGE_name=httpd \
    IMAGE_summary="Apache2 $APACHE_version" \
    IMAGE_description="This UBI minimal based container image runs \
    Apache ${APACHE_version}" \
    IMAGE_title="Apache ${APACHE_version}" \
    HTTPD_port="8080"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="${IMAGE_authors}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.version="${IMAGE_version}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.expose-services="${HTTPD_port}:http" \
      io.openshift.tags="${IMAGE_name},apache,apache-${APACHE_ver_short},apache${APACHE_ver_short}" \
      maintainer="${IMAGE_authors}"

# Container variables
ENV CTR_user=apache \
    CTR_user_id="48" \
    CTR_cmd="httpd -D FOREGROUND"

# Component bash variables
ENV HTTPD_main_conf_path=/etc/httpd/conf \
    HTTPD_main_conf_file=/etc/httpd/conf/httpd.conf \
    HTTPD_main_conf_d_path=/etc/httpd/conf.d \
    HTTPD_modules_conf_d_path=/etc/httpd/conf.modules.d \
    HTTPD_var_run_path=/run/httpd \
    HTTPD_public_path=/var/www/html \
    HTTPD_log_path=/var/log/httpd

COPY conf/usr/bin/* /usr/bin/
COPY conf/container-entrypoint.d/* ${CTR_entrypoint_opt_path}/

RUN container-setup
RUN install-pkgs httpd

# Component config variables
ENV HTTPD_listen=${HTTPD_port} \
    HTTPD_user=${CTR_user} \
    HTTPD_group=${CTR_group} \
    HTTPD_documentroot=${HTTPD_public_path}

RUN httpd-setup

WORKDIR ${HTTPD_public_path}

USER ${CTR_user_id}

STOPSIGNAL SIGWINCH

EXPOSE ${HTTPD_port}

CMD ${CTR_cmd}
