# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

# General ansible variables
ENV IMAGE_authors="{{ dockerfile_builder_image_authors }}" \
    IMAGE_created="{{ dockerfile_builder_image_created }}" \
    CTR_pkg_mgm="{{ dockerfile_builder_pkgs_mgm }}"

# General variables
ENV IMAGE_name=base \
    IMAGE_summary="UBI based image" \
    IMAGE_description="UBI based for building other images" \
    IMAGE_title="UBI based image"

# Labels
LABEL org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.authors="${IMAGE_authors}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.created="${IMAGE_created}" \
      name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},ubi" \
      maintainer="${IMAGE_authors}"

# Container variables
ENV CTR_user=default \
    CTR_user_id="1001" \
    CTR_user_gecos="Default Application User" \
    CTR_group=root \
    CTR_group_id="0" \
    CTR_entrypoint_opt_path=/opt/container-entrypoint.d

# Frequent environment variables
ENV HOME="/opt/${CTR_user}"

# https://github.com/rpm-software-management/microdnf/issues/50
RUN mkdir -p /run/user/$(id -u)

COPY conf/usr/bin/* /usr/bin/

RUN container-setup

ENTRYPOINT ["container-entrypoint"]
