# {{ ansible_managed  }}
FROM {{ dockerfile_builder_image_from }}

ENV IMAGE_AUTHORS="{{ dockerfile_builder_image_authors }}" \
    IMAGE_CREATED="{{ dockerfile_builder_image_created }}" \
    PKGS_MGM="{{ pkgs_mgm }}"

ENV NAME=base \
    SUMMARY="UBI based image" \
    DESCRIPTION="UBI based for building other images" \
    TITLE="UBI based image"

LABEL org.opencontainers.image.title="${TITLE}" \
      org.opencontainers.image.authors="${IMAGE_AUTHORS}" \
      org.opencontainers.image.description="${DESCRIPTION}" \
      org.opencontainers.image.created="${IMAGE_CREATED}" \
      name="${NAME}" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.description="${DESCRIPTION}" \
      io.k8s.display-name="${TITLE}" \
      io.openshift.tags="${NAME},ubi" \
      maintainer="${IMAGE_AUTHORS}"

ENV CUSER=default \
    CUSER_ID="1001" \
    CUSER_GECOS="Default Application User" \
    HOME="/opt/default" \
    CGROUP=root \
    CGROUP_ID="0" \
    ENTRYPOINT_SCRIPTS_PATH=/opt/container-entrypoint.d

# https://github.com/rpm-software-management/microdnf/issues/50
RUN mkdir -p /run/user/$(id -u)

COPY conf/usr/bin/* /usr/bin/

RUN container-setup

ENTRYPOINT ["container-entrypoint"]
