- name: hola
  when: ansible_host in groups[build_step|default('all')]
  block:
  - name: show build group name
    debug:
      msg: "building images in group: {{ build_step|default('all') }}"

  - name: build image
    include_role:
      name: dockerfile_builder

  - name: get build image info
    docker_image_info:
      name: "{{ dockerfile_builder_image }}"
    register: build_image_status

  - name: state image build fact
    when: not ansible_check_mode
    set_fact:
      state_yml_build: true
      state_yml_id: "{{ build_image_status.images[0].Id }}"
