# {{ ansible_managed  }}
FROM {{ image_from }}

ENV APACHE_VERSION="{{ moodle_apache_version }}" \
    APACHE_VER_SHORT="{{ moodle_apache_version | replace('.','') }}" \
    MOODLE_VERSION="{{ moodle_version }}" \
    MOODLE_VER_SHORT="{{ moodle_version | replace('.','') }}" \
    IMAGE_AUTHORS="{{ image_authors }}" \
    TZ="{{ image_timezone }}"

ENV NAME=apache${APACHE_VER_SHORT}_moodle${MOODLE_VER_SHORT} \
    SUMMARY="Apache2 $APACHE_VERSION for Moodle" \
    DESCRIPTION="This UBI based docker image runs \
    Apache APACHE_VERSION for Moodle" \
    TITLE="Apache APACHE_VERSION for Moodle" \
    HTTPD_PORT="8080"

LABEL org.opencontainers.image.title="${TITLE}" \
      org.opencontainers.image.authors="${AUTHORS}" \
      org.opencontainers.image.description="${DESCRIPTION}" \
      org.opencontainers.image.version="${MOODLE_VERSION}" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      io.k8s.description="${DESCRIPTION}" \
      io.k8s.display-name="${TITLE}" \
      io.openshift.expose-services="${HTTPD_PORT}:http" \
      io.openshift.tags="apache,apache${APACHE_VER_SHORT},apache-${APACHE_VER_SHORT},moodle,moodle${MOODLE_VER_SHORT},moodle-${MOODLE_VER_SHORT},${NAME}" \
      maintainer="${IMAGE_AUTHORS}"

ENV CUSER=apache \
    CUSER_ID="48" \
    CMD="httpd -D FOREGROUND"

ENV HTTPD_MAIN_CONF_PATH=/etc/httpd/conf \
    HTTPD_MAIN_CONF_D_PATH=/etc/httpd/conf.d \
    HTTPD_MODULES_CONF_D_PATH=/etc/httpd/conf.modules.d \
    HTTPD_VAR_RUN=/run/httpd \
    HTTPD_PUBLIC_PATH=/var/www/html \
    HTTPD_DATA_ORIG_PATH=/var/www \
    HTTPD_LOG_PATH=/var/log/httpd \
    HTTPD_VAR_PATH=/var

COPY conf/usr/bin/* /usr/bin/

RUN container-setup
RUN install-pkgs httpd
RUN httpd-setup

WORKDIR ${HTTPD_PUBLIC_PATH}

USER ${CUSER_ID}

EXPOSE ${HTTPD_PORT}

ENTRYPOINT ["container-entrypoint"]

CMD $CMD
