# image
dockerfile_builder_image_from: "{{ dest_subdir }}/nginx_php-fpm{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined else '' }}"
dockerfile_builder_image_version: "0.0.1"

# source dir
src_path: "{{ src_dir }}/{{ src_subdir }}/moodle_nginx"
