#!/bin/bash -e
# description: additional entrypoint script for nginx

# nginx default config
sed -i \
    -e "s@__listen__@${NGINX_LISTEN}@" \
    -e "s@__server_name__@${NGINX_SERVER_NAME}@" \
    -e "s@__rootdocument__@${NGINX_DOCUMENTROOT}@" \
    -e "s@__listen_option__@${NGINX_LISTEN_OPTIONS}@" \
    ${NGINX_MAIN_CONF_FILE}
