# options
dockerfile_builder_pull: true

dockerfile_builder_image_from: "{{ registry_path }}/base-stream{{ ':' +
  dockerfile_builder_image_from_tag if
  dockerfile_builder_image_from_tag is defined and dockerfile_builder_image_from_tag else '' }}"
dockerfile_builder_image_based: CentOS 8 Stream
dockerfile_builder_image_ocp_tags: centos,centos8-stream,rootfs-creator
