# image
container_builder_image_from: moodle40

# source dir
template_path: "{{ template_dir }}/moodle_bundle"

# ci
prepare_image_task: moodle
version_release_no_bump: true

# version
version_image_major: "{{ hostvars[container_builder_image_from].moodle_git_source_version.split('.')[0] | default(false) }}"
version_image_minor: "{{ hostvars[container_builder_image_from].moodle_git_source_version.split('.')[1] | default(false) }}"
version_image_patch: "{{ hostvars[container_builder_image_from].moodle_git_source_version.split('.')[2] | default(false) }}"

# moodle
moodle_plugin_list: mod_attendance mod_checklist mod_customcert block_checklist gradeexport_checklist
