# {{ ansible_managed  }}
{% if moodle_app_copy_from is defined %}
FROM {{ moodle_app_copy_from }} AS app
RUN app-git -a -e '.git*'

{% endif %}
FROM {{ dockerfile_builder_image_from }}

# General variables
ENV IMAGE_name="moodle_nginx" \
    IMAGE_summary="Nginx ${NGINX_version} for Moodle {{ moodle_version }}" \
    IMAGE_description="This {{ dockerfile_builder_image_based }} based container image runs Nginx ${NGINX_version} for Moodle {{ moodle_version }}" \
    IMAGE_title="Nginx ${NGINX_version} for Moodle {{ moodle_version }}" \
    TZ="{{ dockerfile_builder_image_timezone }}"

# Component bash variables
ENV APP_dest=/var/www/html

ENV MOODLE_version="{{ moodle_version }}" \
    MOODLE_ver_short="{{ moodle_version | replace('.','') }}" \
    MOODLE_commit="{{ moodle_git_commit }}" \
    MOODLE_app=${APP_dest} \
    MOODLE_data=/var/moodledata \
    MOODLE_check_path=/login/index.php \
    MOODLE_check_code="200" \
    MOODLE_check_host=localhost

USER 0

COPY conf/usr/bin/* /usr/bin/
COPY conf/usr/libexec/* /usr/libexec/
COPY conf/container-entrypoint.d/* ${CTR_entrypoint_opt_path}/

RUN container-setup

{% if moodle_app_copy_from is defined %}
COPY --from={{ moodle_app_copy_from }} ${MOODLE_app} ${MOODLE_app}

{% endif %}
RUN container-setup-nginx-moodle

USER ${CTR_user_id}

# Labels
LABEL name="${IMAGE_name}" \
      summary="${IMAGE_summary}" \
      description="${IMAGE_description}" \
      maintainer="{{ dockerfile_builder_image_authors }}" \
      org.opencontainers.image.title="${IMAGE_title}" \
      org.opencontainers.image.description="${IMAGE_description}" \
      org.opencontainers.image.version="{{ dockerfile_builder_image_version }}" \
      io.k8s.description="${IMAGE_description}" \
      io.k8s.display-name="${IMAGE_title}" \
      io.openshift.tags="${IMAGE_name},nginx,nginx${NGINX_ver_short},nginx-${NGINX_ver_short},moodle,moodle${MOODLE_ver_short},moodle-${MOODLE_ver_short}"
