# platform vars
operator_version: 1.7.2
kustomize_version: 4.1.3
kubectl_version: 1.20.7

container_builder_image_from: ansible-podman-ci
dockerfile_builder_image_ocp_tags: "ansible,ansible{{ image_ansible_version }},ansible-operator,ansible-operator{{ operator_version }}"
