#!/bin/bash -e
# description: additional entrypoint script for nginx

# nginx default config
sed -i \
    -e "s@__listen__@${NGINX_listen}@" \
    -e "s@__server_name__@${NGINX_server_name}@" \
    -e "s@__rootdocument__@${NGINX_documentroot}@" \
    -e "s@__listen_option__@${NGINX_listen_options}@" \
    ${NGINX_main_conf_file}
