- name: create buildx k8s builder for amd64
  when: buildx_k8s_builder_amd64 | default(true)
  command: >-
    docker buildx create --use
    --name=container_builder
    --platform=linux/amd64
    --node=buildkit-amd64
    --driver=kubernetes
    --driver-opt="{{ buildx_k8s_builder_amd64_driver_opt }}"

- name: add buildx k8s builder for arm64
  when: buildx_k8s_builder_arm64 | default(true)
  command: >-
    docker buildx create --append
      --name=container_builder
      --platform=linux/arm64
      --node=buildkit-arm64
      --driver=kubernetes
      --driver-opt="{{ buildx_k8s_builder_arm64_driver_opt }}"
