# platform vars
go_version: "{{ go_versions.122 }}"

version_image_suffix: toolset
template_path: "{{ template_dir }}/go-toolset"

# builder
dockerfile_builder_image_ocp_tags: "go,go-toolset,go{{ go_version }}-toolset"
