rocky_version: 9
image_from_ctr: "rocky{{ rocky_version }}-base"
image_tag_from_ctr: "{{ rocky_version }}-base"
dockerfile_builder_image_from_repo_name: rocky
dockerfile_builder_image_based: "Rocky Linux {{ rocky_version }} minimal"
