apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: pullrequest
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@4a2339d4be2ca7f857302ac9441cac7966bfb875
            - image: quay.io/krestomatio/ansible-docker-ci
              name: build-containers
              args:
                - .ansible-ci/build.yml
              command:
                - ansible-playbook
              volumeMounts:
                - name: libdocker
                  mountPath: /var/lib/docker
              securityContext:
                privileged: true
            volumes:
              - name: libdocker
                persistentVolumeClaim:
                  claimName: libdocker-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
