apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/krestomatio/jx3-pipeline-catalog/48cf2f2a325dd954fb1a08080ee03cc3904840da/tasks/git-clone/git-clone-pr.yaml
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: PIPELINE_KIND
            value: pullrequest
          - name: JX_BATCH_MODE
            value: "true"
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - args:
          - ansible-playbook build.yml
          command:
          - /bin/sh
          - -c
          env:
          - name: CLOUD_PROVIDER
            value: m6e
          image: krestomatio/ansible-docker-ci
          name: build-containers
          securityContext:
            privileged: true
          workingDir: /workspace/source
          resources: {}
          volumeMounts:
          - name: libdocker
            mountPath: /var/lib/docker
        volumes:
        - name: libdocker
          persistentVolumeClaim:
            claimName: libdocker-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
