apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
      - name: pullrequest
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            env:
              - name: HOME
                value: /tekton/home
              - name: CLOUD_PROVIDER
                value: kio
            resources:
              limits:
                cpu: 1000m
                memory: 2048Mi
              requests:
                cpu: 50m
                memory: 32Mi
            workingDir: /workspace/source
            volumeMounts:
              - name: shared
                mountPath: /shared
          steps:
            - image: quay.io/krestomatio/ansible-docker-ci:0.2.3
              name: build-containers
              script: |
                #!/bin/bash -eu
                ansible-playbook .ansible-ci/build.yml
              volumeMounts:
                - name: libdocker
                  mountPath: /var/lib/docker
              resources:
                requests:
                  cpu: 0.1
                  memory: 128Mi
          volumes:
            - name: libdocker
              persistentVolumeClaim:
                claimName: libdocker-0sd6j3-pvc
            - name: shared
              persistentVolumeClaim:
                claimName: shared-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
