apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: pullrequest
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            env:
              - name: HOME
                value: /tekton/home
            resources:
              limits:
                cpu: 1000m
                memory: 2048Mi
              requests:
                cpu: 50m
                memory: 32Mi
            workingDir: /workspace/source
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@e3ba7ae6c62bc3ee26c073920d5662556a21f51f
            - image: quay.io/krestomatio/ansible-docker-ci
              name: build-containers
              env:
                - name: DOCKER_HOST
                  value:
              envFrom:
              - secretRef:
                  name: multiarch-builder-envvars
                  optional: true
              script: |
                #!/bin/bash -eu
                ansible-playbook .ansible-ci/build.yml -e terraform_multiarch_builder=true
              volumeMounts:
                - name: libdocker
                  mountPath: /var/lib/docker
              resources:
                requests:
                  cpu: 0.1
                  memory: 128Mi
          volumes:
            - name: libdocker
              persistentVolumeClaim:
                claimName: libdocker-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
