apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        persistentVolumeReclaimPolicy: Delete
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
    - name: git-clone-pr
      workspaces:
      - name: output
        workspace: shared-workspace
      taskRef:
        name: git-clone-pr
    - name: multiarch-builder-config
      workspaces:
      - name: output
        workspace: shared-workspace
      taskRef:
        name: multiarch-builder-config
    - name: pullrequest
      resources: {}
      timeout: "2h0m0s"
      runAfter:
      - git-clone-pr
      - multiarch-builder-config
      workspaces:
      - name: source
        workspace: shared-workspace
      taskSpec:
        metadata: {}
        workspaces:
        - name: source
          mountPath: /workspace
        volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-0sd6j3-pvc
        stepTemplate:
          name: ''
          env:
          - name: HOME
            value: /workspace
          - name: CLOUD_PROVIDER
            value: kio
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 32Mi
          workingDir: /workspace/source
          volumeMounts:
          - name: shared
            mountPath: /shared
        steps:
        - image: quay.io/krestomatio/ansible-docker-ci
          name: build-containers
          script: |
            #!/bin/bash -eu
            ansible-playbook .ansible-ci/build.yml
          resources:
            limits:
              cpu: 1.5
              memory: 4096Mi
            requests:
              cpu: 0.1
              memory: 128Mi
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
