apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: pullrequest
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            env:
              - name: HOME
                value: /tekton/home
              - name: TERRAFORM_WORKING_DIR
                value: "/shared/$(params.REPO_OWNER)/$(params.REPO_NAME)/$(params.JOB_NAME)/$(params.PULL_NUMBER)/multiarch-builder"
              - name: TF_VAR_prefix_name
                value: "$(params.REPO_OWNER)-$(params.REPO_NAME)-$(params.JOB_NAME)-$(params.PULL_NUMBER)"
            resources:
              limits:
                cpu: 1000m
                memory: 2048Mi
              requests:
                cpu: 50m
                memory: 32Mi
            workingDir: /workspace/source
            volumeMounts:
              - name: shared
                mountPath: /shared
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@1d617dda837673daa9fb677a31dd25fc0ff667d9
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/multiarch-builder/ecr-public-login.yaml@1d617dda837673daa9fb677a31dd25fc0ff667d9
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/multiarch-builder/deploy.yaml@1d617dda837673daa9fb677a31dd25fc0ff667d9
            - image: quay.io/krestomatio/ansible-docker-ci:0.2.3
              name: build-containers
              script: |
                #!/bin/bash -eu
                ansible-playbook .ansible-ci/build.yml
              volumeMounts:
                - name: libdocker
                  mountPath: /var/lib/docker
              resources:
                requests:
                  cpu: 0.1
                  memory: 128Mi
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/multiarch-builder/undeploy.yaml@1d617dda837673daa9fb677a31dd25fc0ff667d9
          volumes:
            - name: libdocker
              persistentVolumeClaim:
                claimName: libdocker-0sd6j3-pvc
            - name: shared
              persistentVolumeClaim:
                claimName: shared-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
