apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        persistentVolumeReclaimPolicy: Delete
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
    - name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace
      taskRef:
        name: git-clone
    - name: release
      resources: {}
      timeout: "2h0m0s"
      runAfter:
      - git-clone
      workspaces:
      - name: source
        workspace: shared-workspace
      taskSpec:
        metadata: {}
        workspaces:
        - name: source
          mountPath: /workspace
        stepTemplate:
          name: ''
          env:
          - name: HOME
            value: /workspace
          - name: CLOUD_PROVIDER
            value: kio
          - name: GIT_AUTHOR_NAME
            value: krestomatio-cibot
          - name: GIT_AUTHOR_EMAIL
            value: jobcespedes@krestomatio.com
          - name: GIT_COMMITTER_NAME
            value: krestomatio-cibot
          - name: GIT_COMMITTER_EMAIL
            value: jobcespedes@krestomatio.com
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 32Mi
          workingDir: /workspace/source
        steps:
        - image: quay.io/krestomatio/ansible-docker-ci
          name: release
          env:
          - name: APIKEY__QUAY_IO
            valueFrom:
              secretKeyRef:
                key: apikey
                name: quay-io-api-key
          - name: APIKEY_GITLAB
            valueFrom:
              secretKeyRef:
                key: apikey
                name: gitlab-api-key
          - name: USERNAME_GITLAB
            valueFrom:
              secretKeyRef:
                key: username
                name: tekton-git
          script: |
            #!/bin/bash
            ## add gitlab lfs api
            echo "https://${USERNAME_GITLAB}:${APIKEY_GITLAB}@gitlab.com" >> ~/.git-credentials
            ## run release play
            NEXT_VERSION=${VERSION} ansible-playbook .ansible-ci/release.yml
          resources:
            limits:
              cpu: 1.5
              memory: 4096Mi
            requests:
              cpu: 0.1
              memory: 128Mi
        - name: promote
          image: ghcr.io/jenkins-x/jx-updatebot:0.0.86
          script: |
            #!/bin/bash
            HEAD_COMMIT=$(git rev-parse HEAD 2> /dev/null || echo)

            # promote if a new commit is made during pipeline
            if [[ ! -z ${HEAD_COMMIT} && ! -z ${PULL_BASE_SHA} && "${HEAD_COMMIT}" != "${PULL_BASE_SHA}" ]]; then
              jx-updatebot pr -c .lighthouse/updatebot-ansible-collection.yaml \
                  --commit-title "chore: bump image versions in ansible collection with updatebot" \
                  --no-version
            else
              echo "not promoted"
            fi
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
