apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: release
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ''
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:krestomatio/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@1a6580e62be0986d18dbb1c42327231ccc378e7c
            - image: quay.io/krestomatio/ansible-docker-ci
              name: gitlab-lfs
              env:
              - name: APIKEY_GITLAB
                valueFrom:
                  secretKeyRef:
                    key: apikey
                    name: gitlab-api-key
              - name: USERNAME_GITLAB
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: tekton-git
              script: |
                #!/bin/bash
                echo "https://${USERNAME_GITLAB}:${APIKEY_GITLAB}@gitlab.com" >> ~/.git-credentials
            - image: quay.io/krestomatio/ansible-docker-ci
              name: release
              env:
              - name: CLOUD_PROVIDER
                value: m6e
              - name: APIKEY__QUAY_IO
                valueFrom:
                  secretKeyRef:
                    key: apikey
                    name: quay-io-api-key
              args:
              - .ansible-ci/release.yml
              command:
              - ansible-playbook
              volumeMounts:
              - name: libdocker
                mountPath: /var/lib/docker
          volumes:
          - name: libdocker
            persistentVolumeClaim:
              claimName: libdocker-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
