apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/krestomatio/jx3-pipeline-catalog/master/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    params:
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: revision
      type: string
    tasks:
    - name: from-build-pack
      params:
      - name: revision
        value: $(params.revision)
      resources: {}
      taskSpec:
        metadata: {}
        params:
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        stepTemplate:
          env:
          - name: PIPELINE_KIND
            value: release
          - name: JX_BATCH_MODE
            value: "true"
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - args:
          - ansible-playbook release.yml
          command:
          - /bin/sh
          - -c
          env:
          - name: CLOUD_PROVIDER
            value: m6e
          image: krestomatio/ansible-docker-ci
          name: release
          workingDir: /workspace/source
          resources: {}
          volumeMounts:
          - name: libdocker
            mountPath: /var/lib/docker
        volumes:
        - name: libdocker
          persistentVolumeClaim:
            claimName: libdocker-0sd6j3-pvc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
