version_include_fallback_tags: true
pr_commit_tag:
  "{{ lookup('env','PULL_PULL_SHA') | default(git_head_commit,true) |
  default(lookup('pipe', 'git rev-parse HEAD 2> /dev/null  || echo')) |
  default(false) }}"
version_commit_tag: "{{ pr_commit_tag }}"
version_image_prerelease: "{{ lookup('env','BRANCH_NAME') |
default(false,true) }}"
version_image_build: "{{ lookup('env','BUILD_ID') | default(version_commit_tag[:7],true) | default(false) }}"
artifact_tag: "{{ pr_commit_tag }}"
state_yml_artifact_tag: "{{ artifact_tag }}"
assertion_artifact_tag: true
