version_add_build: true
version_include_fallback_tags: true
pr_commit_tag: "{{ lookup('env','PULL_PULL_SHA') | default(false) }}"
version_commit_tag: "{{ pr_commit_tag }}"
artifact_tag: "{{ pr_commit_tag }}"
state_yml_artifact_tag: "{{ artifact_tag }}"
state_path: "{{ working_dir }}/vars/tmp/state"
assertion_artifact_tag: true
end_host: false
end_host_msg: "artifact tag for pipeline does not match the one in state image file"
